config/routes.rb
Rails.application.routes.draw do
  devise_for :games
  devise_for :users
  devise_for :admins, controllers: { registrations: 'admins/registrations', sessions: 'admins/sessions', passwords: 'admins/passwords', confirmations: 'admins/confirmations', unlocks: 'admins/unlocks'}
  resource :cards
  resource :plans

  # root to: 'games#show'
  patch 'game_mobile_user/accept_user/:user_id', to: 'game_mobile_user#accept_user', as: 'accept_user'
  patch 'game_mobile_user/reject_user/:user_id', to: 'game_mobile_user#reject_user', as: 'reject_user'
 
###########
# Landing #
###########
  root 'landing#index'
  get 'admins/:admin_id/confirm', to: "landing#after_confirm", as: 'admin_after_confirm'
  get 'cookies', to: 'landing#accept_cookies', as: 'accept_cookies'
  get '/contact', to: 'landing#contact', as: 'contact'
  get 'product', to: 'landing#product', as: 'product'
  get 'datenschutz', to: 'landing#datenschutz', as: 'datenschutz'
  get 'impressum', to: 'landing#impressum', as: 'impressum'
  get 'blog', to: 'landing#blog', as: 'blog'
  get 'blog/:blog_id', to: 'landing#show_blog', as: 'show_blog'
	
  get 'landing/ended_game', to: 'landing#ended_game', as: 'landing_ended_game'

  get '/byebye', to: 'landing#byebye', as: 'byebye'
  # patch 'verification/verify_token' ,to: 'verification#verify_token' , as:'verify_token'
  get 'admins/register', to: 'landing#register', as: 'register'
  get 'admins/signup/:v_id', to: 'landing#signup' , as: 'edit_next_admin'
  patch 'admins/update_admin/:v_id', to: 'landing#update_admin', as: 'update_admin'
  patch 'admins/update_admin_details/:v_id', to: 'landing#update_admin_details', as: 'update_admin_details'

  get 'coaches/info', to: 'landing#coach', as: 'coach_info'
  # get '/verfication/:token' , to: 'verification#token' , as: 'verification_token'
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
########
# Game #
########

#################
# Admin Desktop #
#################

  get 'games/wait', to: 'game_desktop_admin#wait', as: 'gda_wait'
  get 'games/intro', to: 'game_desktop_admin#intro', as: 'gda_intro'
  get 'games/youtube_video', to: 'game_desktop_admin#youtube_video', as: 'gda_youtube'
  get 'games/choose', to: 'game_desktop_admin#choose', as: 'gda_choose'
  get 'games/turn', to: 'game_desktop_admin#turn', as: 'gda_turn'
  get 'games/error', to: 'game_desktop_admin#error', as: 'gea_turn'
  get 'video_testing', to: 'game_mobile_admin#video_testing'
  get 'games/play', to: 'game_desktop_admin#play', as: 'gda_play'
  get 'games/rate', to: 'game_desktop_admin#rate', as: 'gda_rate'
  get 'games/rating', to: 'game_desktop_admin#rating', as: 'gda_rating'
  get 'games/skip_rating', to: 'game_desktop_admin#skip_rating', as: 'gda_skip_rating'
  get 'games/bestlist', to: 'game_desktop_admin#bestlist', as: 'gda_bestlist'
  get 'games/ended', to: 'game_desktop_admin#ended', as: 'gda_ended'
  get 'games/ended_game', to: 'game_desktop_admin#ended_game', as: 'gda_ended_game'
  get 'games/replay', to: 'game_desktop_admin#replay', as: 'gda_replay'
    
  get 'games/after_rating', to: 'game_desktop_admin#after_rating', as: 'gda_after_rating'
  get 'games/video_uploaded_status', to: 'game_desktop_admin#video_uploaded_status', as: 'gda_video_uploaded_status'
  

################
# Admin Mobile #
################

  
  get 'mobile/admins/:password', to: 'game_mobile_admin#new', as: 'gma_start'
  post 'mobile/admins/:password', to: 'game_mobile_admin#create'
  get 'mobile/admin/avatar', to: 'game_mobile_admin#new_avatar', as: 'gma_new_avatar'
  post 'mobile/admin/avatar', to: 'game_mobile_admin#create_avatar'
  get 'mobile/admin/new_turn', to: 'game_mobile_admin#new_turn', as: 'gma_new_turn'
  post 'mobile/admin/new_turn', to: 'game_mobile_admin#create_turn'
    
  get 'mobile/admin/wait', to: 'game_mobile_admin#wait', as: 'gma_wait'
  post 'mobile/admin/after_wait', to: 'game_mobile_admin#after_wait', as: 'gma_after_wait'
  post 'mobile/admin/before_intro', to: 'game_mobile_admin#before_intro', as: 'gma_before_intro'
  get 'mobile/admin/intro', to: 'game_mobile_admin#intro', as: 'gma_intro'
  get 'mobile/admin/select_user', to: 'game_mobile_admin#choose_rating_user', as: 'gma_choose_rating_user'
  get 'mobile/admin/youtube_video', to: 'game_mobile_admin#youtube_video', as: 'gma_youtube'
  get 'mobile/admin/error', to: 'game_mobile_admin#error', as: 'gea_mobile'
  get 'mobile/admin/choose', to: 'game_mobile_admin#choose', as: 'gma_choose'
  get 'mobile/admin/choosen/:turn_id', to: 'game_mobile_admin#choosen', as: 'gma_choosen'
  get 'mobile/admin/turn', to: 'game_mobile_admin#turn', as: 'gma_turn'
  get 'mobile/admin/play', to: 'game_mobile_admin#play', as: 'gma_play'
  get 'mobile/admin/react', to: 'game_mobile_admin#react', as: 'gma_react'
  post 'mobile/admin/upload', to: 'game_mobile_admin#save_video', as: 'gpitchsave_play'
  get 'mobile/admin/video_cancel', to: 'game_mobile_admin#video_cancel',as: 'cancel_video_uploading'
  get 'mobile/admin/rate', to: 'game_mobile_admin#rate', as: 'gma_rate'
  get 'mobile/admin/rated', to: 'game_mobile_admin#rated', as: 'gma_rated'
  get 'mobile/admin/rating', to: 'game_mobile_admin#rating', as: 'gma_rating'
  get 'mobile/admin/skip_rating', to: 'game_mobile_admin#skip_rating', as: 'gma_skip_rating'
  get 'mobile/admin/bestlist', to: 'game_mobile_admin#bestlist', as: 'gma_bestlist'
  get 'mobile/admin/replay', to: 'game_mobile_admin#replay', as: 'gma_replay'
  get 'mobile/admin/ended', to: 'game_mobile_admin#ended', as: 'gma_ended'
  get 'mobile/admin/ended_game', to: 'game_mobile_admin#ended_game', as: 'gma_ended_game'
  get 'mobile/admin/after_rating', to: 'game_mobile_admin#after_rating', as: 'gma_after_rating'
  post 'mobile/admin/update_video_status', to: 'game_mobile_admin#update_video_status', as: 'gma_update_video_status'

    
###############
# User Mobile #
###############
    
  get 'mobile/user/game', to: 'game_mobile_user#new', as: 'gmu_password'
  post 'mobile/user/game', to: 'game_mobile_user#create'

  get 'mobile/user/name', to: 'game_mobile_user#new_name', as: 'gmu_new_name'
  post 'mobile/user/name', to: 'game_mobile_user#create_name'
    
  get 'mobile/user/company', to: 'game_mobile_user#new_company', as: 'gmu_new_company'
  post 'mobile/user/company', to: 'game_mobile_user#create_company'
    
  get 'mobile/user/avatar', to: 'game_mobile_user#new_avatar', as: 'gmu_new_avatar'
  post 'mobile/user/avatar', to: 'game_mobile_user#create_avatar'
    
  get 'mobile/user/game/new_turn', to: 'game_mobile_user#new_turn', as: 'gmu_new_turn'
  post 'mobile/user/game/new_turn', to: 'game_mobile_user#create_turn'
  get 'mobile/user/game/vidoe_uploading', to: 'game_mobile_user#video_uploading', as: 'gmu_video_check'
  get 'mobile/user/game/wait', to: 'game_mobile_user#wait', as: 'gmu_wait'
  get 'mobile/user/game/intro', to: 'game_mobile_user#intro', as: 'gmu_intro'
  get 'mobile/user/game/choose', to: 'game_mobile_user#choose', as: 'gmu_choose'
  get 'mobile/user/game/choosen/:turn_id', to: 'game_mobile_user#choosen', as: 'gmu_choosen'
  get 'mobile/user/game/turn', to: 'game_mobile_user#turn', as: 'gmu_turn'
  get 'mobile/user/game/play', to: 'game_mobile_user#play', as: 'gmu_play'
  get 'mobile/user/game/react', to: 'game_mobile_user#react', as: 'gmu_react'
  get 'mobile/user/game/rate', to: 'game_mobile_user#rate', as: 'gmu_rate'
  get 'mobile/user/game/rated', to: 'game_mobile_user#rated', as: 'gmu_rated'
  get 'mobile/user/game/rating', to: 'game_mobile_user#rating', as: 'gmu_rating'
  get 'mobile/user/game/skip_rating', to: 'game_mobile_user#skip_rating', as: 'gmu_skip_rating'
  get 'mobile/user/game/bestlist', to: 'game_mobile_user#bestlist', as: 'gmu_bestlist'
  get 'mobile/user/game/replay', to: 'game_mobile_user#replay', as: 'gmu_replay'
  get 'mobile/user/game/ended', to: 'game_mobile_user#ended', as: 'gmu_ended'
  get 'mobile/user/game/ended_game', to: 'game_mobile_user#ended_game', as: 'gmu_ended_game'
	
############
# Vertrieb #
############
	
  get '/vertrieb', to: 'vertrieb#new', as: 'vertrieb'
  post 'vertrieb/new', to: 'vertrieb#create', as: 'new_vertrieb'
  post 'vertrieb/login', to: 'vertrieb#login', as: 'login_vertrieb'
 
  get 'vertrieb/start', to: 'vertrieb#start', as: 'start_vertrieb'
  get 'vertrieb/proceed', to: 'vertrieb#proceed', as: 'proceed_vertrieb'
	
  get "vertrieb/game_wait", to: "vertrieb#game_wait", as: 'game_wait_vertrieb'
  get 'vertrieb/game_choose', to: 'vertrieb#game_choose', as: 'game_choose_vertrieb'
  get 'vertrieb/game_turn', to: 'vertrieb#game_turn', as: 'game_turn_vertrieb'
  get 'vertrieb/game_play', to: 'vertrieb#game_play', as: 'game_play_vertrieb'
  get 'vertrieb/game_rate', to: 'vertrieb#game_rate', as: 'game_rate_vertrieb'
  get 'vertrieb/game_rated', to: "vertrieb#game_rated", as: 'game_rated_vertrieb'
  get 'vertrieb/game_bestlist', to: 'vertrieb#game_bestlist', as: 'game_bestlist_vertrieb'
	
  get 'vertrieb/dash_customize', to: 'vertrieb#dash_customize', as: 'dash_customize_vertrieb'
  get 'vertrieb/dash_lets_pitch', to: 'vertrieb#dash_lets_pitch', as: 'dash_lets_pitch_vertrieb'
  get 'vertrieb/dash_lets_pitch2', to: 'vertrieb#dash_lets_pitch2', as: 'dash_lets_pitch2_vertrieb'
  get 'vertrieb/dash_user_stats', to: 'vertrieb#dash_user_stats', as: 'dash_user_stats_vertrieb'
  get 'vertrieb/dash_users', to: 'vertrieb#dash_users', as: 'dash_users_vertrieb'
  get 'vertrieb/dash_videoanalyse', to: 'vertrieb#dash_videoanalyse', as: 'dash_videoanalyse_vertrieb'
	
  get 'vertrieb/ended', to: 'vertrieb#ended', as: 'ended_vertrieb'
    
####################################################################################
#############
# Dashboard #
#############

##############
# Backoffice #
##############
  
  get 'backoffice', to: 'backoffice#index', as: 'backoffice'
	
  get 'backoffice/admins', to: 'backoffice#admins', as: 'backoffice_admins'
  get 'backoffice/admins/:admin_id', to: 'backoffice#admin', as: 'backoffice_admin'

app/controllers/landing_controller.rb
class LandingController < ApplicationController

  # skip_before_action :check_expiration_date, only: :price
  before_action :check_sessions, only: [:index,:price, :product]

  layout 'main'
  respond_to :html, :json

  def after_confirm
	@admin = Admin.find(params[:admin_id])
  end
  def accept_cookies
	cookies[:accepted] = 'true'
	redirect_to root_path
  end

  def datenschutz
  end
  def impressum
  end
  def product
  end
	
  def index
  end

  def blog
	@blogs = Blog.all
	@blog = @blogs.count == 0 ? nil : @blogs.last
  end
  def show_blog
	@blog = Blog.find(params[:blog_id])
	@blogs = Blog.where.not(id: @blog.id).last(3)
  end
  def ended_game
	if !current_admin.nil?
	  sign_out(current_admin)
	end
	if !current_game.nil?
	  sign_out(current_game)
	end
	if !current_user.nil?
      sign_out(current_user)
	end
  end
    
  def contact
  end
    
  def byebye
  end

  private 
    def check_sessions   
      return redirect_to dash_admin_path if current_admin.present?   
      return redirect_to dash_user_stats_path if current_user.present?   
    end

    def admin_params
      params.require(:admin).permit( :id, :company_name, :fname, :lname, :street,
        :city, :employees, :zipcode, :male ,:members ,:vid_token, :password , 
        :expiration ,:password_confirm)
    end
end

app/views/landing/blog.html.erb
<% content_for :title, "Peter Pitch - Blog" %>
<% content_for :description, 'Peter Pitch ist das digitale Trainingstool für Kommunikation und Vertrieb! Erfahre mehr und lese dir unsere Interessanten Blog beiträge durch!'%>
<section id="navbar">
    <%= link_to image_tag('landing/logo.png'), root_path, class: 'logo'%>
    <div class="navbar-links" id="navLinks">
       	<div class="link">
       		<%= link_to 'Produkt', product_path %>
       		<div class="line"></div>
       	</div>
        <div class="link">
            <%= link_to 'FAQ', root_path(anchor: 'faq') %>
            <div class="line"></div>
        </div>
        <div class="link">
            <%= link_to 'Kontakt', contact_path %>
            <div class="line"></div>
        </div>
        <div class="link">
            <%= link_to 'Blog', blog_path %>
            <div class="line"></div>
        </div>
        <div class="link">
          	<i class="login-link" onclick="showLoginModal()">Login</i>
        </div>
        <div class="link">
            <%= link_to 'Demo vereinbaren', contact_path("", subject: "demo"), class: 'btn btn-white' %>
        </div>
    </div>
    <div class="login">
       	<i class="login-link" onclick="showLoginModal()">Login</i>
    </div>
    <div class="navbar-mobile" onclick="showNavLinks()">
        <i class="fas fa-bars"></i>
    </div>
</section>
<% if @blog %>
<div class="blog_card">
	<div class="content">
	<%= image_tag @blog.image? ? @blog.image.url : '' %>
	<h5><%= @blog.created_at.strftime("%d.%m.%Y") %></h5>
	<h1><%= @blog.title %></h1>
	<div class="text">
		<% @blog.text.split(%r{\r\n}).each do |be| %>
			<%= be %> <br>
		<% end %>
	</div>
	<%= link_to 'mehr lesen', show_blog_path(@blog) %>
	</div>
</div>
<% end %>
<section id="blog">
	<% @blogs.each do |b| %>
	<div class="card">
		<%= image_tag b.image? ? b.image.url : '' %>
		<h5><%= b.created_at.strftime("%d.%m.%Y") %></h5>
		<h3>
			<%= b.title %>
			
		</h3>
		<div class="text">
			<% b.text.split(%r{\r\n}).each do |bt| %>
				<%= bt %><br>
			<% end %>
		</div>
		<%= link_to '', show_blog_path(b.id) %>
	</div>
	<% end %>
</section>
<section id="content">
	<section id="beratung">
		<h2>Mache aus deinen Mitarbeitern wahre Wölfe!</h2>
		<div class="text">
			Sprich uns an und erfahre, wie Peter Pitch auch deine Schulungen revolutionieren kann.
		</div>
		<%= link_to 'Beratung vereinbaren!', contact_path, class: 'btn btn-green' %>
	</section>
</section>
<section id="footer" class="wow fadeIn">
    <div class="logo">
        <%= image_tag 'landing/logo.png', alt: 'Peter Pitch Logo' %>
    </div>
    <div class="company">
        <div class="heading">Unternehmen</div>
        <div class="links">
            <%= link_to 'Registrieren', contact_path %>
            <%= link_to 'Preise', contact_path %>
            <%= link_to 'FAQ', root_path(anchor: 'faq') %>
            <%= link_to 'Login', '#login', onclick: 'showLoginModal()' %>
        </div>
    </div>
    <div class="legal">
        <div class="heading">Rechtliches</div>
        <div class="links">
            <%= link_to 'Impressum', impressum_path %>
            <%= link_to 'Datenschutz', datenschutz_path %>
        </div>
    </div>
    <div class="social">
        <%= link_to '', 'https://www.instagram.com/peterpitchcom/', target: "_blank", rel: "noopener noreferrer", class: "fab fa-instagram" %>
        <%= link_to '', 'https://www.youtube.com/channel/UCN7MeKNNdXK28uIiJjJ4Fdg', target: "_blank", rel: "noopener noreferrer", class: "fab fa-youtube" %>
        <%= link_to '', 'https://www.facebook.com/PeterPitchCom/', target: "_blank", rel: "noopener noreferrer", class: "fab fa-facebook-f" %>
    </div>
</section>
<div class="fullscreen-modal" id="loginModal">
    
    <div class="close"><i class="fas fa-times" onclick="showLoginModal()"></i></div>
    <div class="card">
    <%= form_for(:admin, as: Admin, url: session_path(Admin)) do |f| %>
        <h2>Login</h2>
        <div class="form-group ">
            <label for="">Email</label>
            <%= f.email_field :email, class: 'form-field', id: 'loginEmail', required: true  %>
        </div>
        <div class="form-group">
            <label for="">Passwort</label>
            <div class="right"><%= link_to "Passwort vergessen?", new_password_path(Admin) %></div>
            <%= f.password_field :password, class: 'form-field',id: 'loginPassword', required: true  %>
            <br>
        </div>
        <div class="form-group center">
            <%= f.submit 'Login', class: 'btn btn-green', id: "loginButton" %>
        </div>
    <% end %>
    </div>
</div>
<script>
    function showLoginModal() {
        $('#loginModal').toggle();
    }
</script>

app/views/landing/ended_game.html.erb
<% content_for :title, "Peter Pitch - Spiel beendet!" %>
<div class="nunito-regular landing-page-content">
    <h1>Bis später, Peter!</h1>
    <div class="logo-container">
        <%= image_tag ("logo-new.png") , alt:"IMG"%>
    </div>
</div>

<style>
    .landing-page-content {
        color: white;
        height: 100vh;
        background: linear-gradient(#1dacf1 0%, #1a8ed6 51%, #145daa 100%);
        display: flex;
        align-items: center;
        justify-content: center;
        flex-direction: column;
    }

    .landing-page-content img {
        width: 45vh;
    }
</style>

app/views/landing/show_blog.html.erb
<% content_for :title, "Peter Pitch - " + @blog.title %>
<% content_for :description, @blog.text %>
<section id="navbar">
    <%= link_to image_tag('landing/logo.png', alt: 'Peter Pitch Logo'), root_path, class: 'logo'%>
    <div class="navbar-links" id="navLinks">
       	<div class="link">
       		<%= link_to 'Produkt', product_path %>
       		<div class="line"></div>
       	</div>
        <div class="link">
            <%= link_to 'FAQ', root_path(anchor: 'faq') %>
            <div class="line"></div>
        </div>
        <div class="link">
            <%= link_to 'Kontakt', contact_path %>
            <div class="line"></div>
        </div>
        <div class="link">
            <%= link_to 'Blog', blog_path %>
            <div class="line"></div>
        </div>
        <div class="link">
          	<i class="login-link" onclick="showLoginModal()">Login</i>
        </div>
        <div class="link">
            <%= link_to 'Demo vereinbaren', contact_path("", subject: "demo"), class: 'btn btn-white' %>
        </div>
    </div>
    <div class="login">
        <i class="login-link" onclick="showLoginModal()">Login</i>
    </div>
    <div class="navbar-mobile" onclick="showNavLinks()">
        <i class="fas fa-bars"></i>
    </div>
</section>
<section id="blog-entry">
	<div class="head">
		<h1><%= @blog.title %></h1>
	</div>
	<%= image_tag @blog.image? ? @blog.image.url : '' %>
	
	<div class="blog">
		<% @blog.blog_paragraphs.each do |bp| %>
		<% if bp.title != '' %><h4><%= bp.title %></h4><% end %>
		<div class="text">
			<% bp.text.split(%r{\r\n}).each do |bt| %>
				<%= bt %><br>
			<% end %>
		</div>
		<% end %>
		<%= image_tag 'landing/shape.svg', class: 'shape s310', id: 'shape1', alt: '' %>
    	<%= image_tag 'landing/shape_green.svg', class: 'shape s153', id: 'shape2', alt: '' %>
    	<%= image_tag 'landing/shape_green.svg', class: 'shape s310', id: 'shape3', alt: '' %>
    	<%= image_tag 'landing/shape.svg', class: 'shape s153', id: 'shape4', alt: '' %>
    	<%= image_tag 'landing/shape_green.svg', class: 'shape s310', id: 'shape5', alt: '' %>
    	<%= image_tag 'landing/shape.svg', class: 'shape s153', id: 'shape6', alt: '' %>
    	<%= image_tag 'landing/shape.svg', class: 'shape s310', id: 'shape7', alt: '' %>
    	<%= image_tag 'landing/shape_green.svg', class: 'shape s153', id: 'shape8', alt: '' %>
    	<%= image_tag 'landing/shape_green.svg', class: 'shape s310', id: 'shape9', alt: '' %>
    	<%= image_tag 'landing/shape.svg', class: 'shape s153', id: 'shape10', alt: '' %>
    	<%= image_tag 'landing/shape.svg', class: 'shape s310', id: 'shape11', alt: '' %>
    	<%= image_tag 'landing/shape_green.svg', class: 'shape s153', id: 'shape12', alt: '' %>
    	<%= image_tag 'landing/shape_green.svg', class: 'shape s310', id: 'shape13', alt: '' %>
    	<%= image_tag 'landing/shape.svg', class: 'shape s153', id: 'shape14', alt: '' %>
    	<%= image_tag 'landing/shape.svg', class: 'shape s310', id: 'shape15', alt: '' %>
    	<%= image_tag 'landing/shape_green.svg', class: 'shape s153', id: 'shape16', alt: '' %>
    	<%= image_tag 'landing/shape_green.svg', class: 'shape s310', id: 'shape17', alt: '' %>
    	<%= image_tag 'landing/shape.svg', class: 'shape s153', id: 'shape18', alt: '' %>
    	<%= image_tag 'landing/shape.svg', class: 'shape s310', id: 'shape19', alt: '' %>
    	<%= image_tag 'landing/shape_green.svg', class: 'shape s153', id: 'shape20', alt: '' %>
	</div>
</section>
<section id="social-links">
	<%= link_to '', 'https://www.instagram.com/peterpitchcom/', target: "_blank", rel: "noopener noreferrer", class: "fab fa-instagram" %>
   <%= link_to '', 'https://www.youtube.com/channel/UCN7MeKNNdXK28uIiJjJ4Fdg', target: "_blank", rel: "noopener noreferrer", class: "fab fa-youtube" %>
   <%= link_to '', 'https://www.facebook.com/PeterPitchCom/', target: "_blank", rel: "noopener noreferrer", class: "fab fa-facebook-f" %>
</section>
<h2 style="text-align: center">Weitere Artikel</h2>
<section id="blog">
		<% @blogs.each do |b| %>
		<div class="card">
		<%= image_tag b.image? ? b.image.url : '' %>
		
		<h5><%= b.created_at.strftime("%d.%m.%Y") %></h5>
		<h3>
			<%= b.title %>
			
		</h3>
		<div class="text">
			<% b.text.split(%r{\r\n}).each do |bt| %>
				<%= bt %><br>
			<% end %>
		</div>
		<%= link_to '', show_blog_path(b.id) %>
		</div>
		<% end %>
</section>
<section id="footer" class="wow fadeIn">
    <div class="logo">
        <%= image_tag 'landing/logo.png', alt: 'Peter Pitch Logo' %>
    </div>
    <div class="company">
        <div class="heading">Unternehmen</div>
        <div class="links">
            <%= link_to 'Registrieren', contact_path %>
            <%= link_to 'Preise', contact_path %>
            <%= link_to 'FAQ', root_path(anchor: 'faq') %>
            <%= link_to 'Login', '#login', onclick: 'showLoginModal()' %>
        </div>
    </div>
    <div class="legal">
        <div class="heading">Rechtliches</div>
        <div class="links">
            <%= link_to 'Impressum', impressum_path %>
            <%= link_to 'Datenschutz', datenschutz_path %>
        </div>
    </div>
    <div class="social">
        <%= link_to '', 'https://www.instagram.com/peterpitchcom/', target: "_blank", rel: "noopener noreferrer", class: "fab fa-instagram" %>
        <%= link_to '', 'https://www.youtube.com/channel/UCN7MeKNNdXK28uIiJjJ4Fdg', target: "_blank", rel: "noopener noreferrer", class: "fab fa-youtube" %>
        <%= link_to '', 'https://www.facebook.com/PeterPitchCom/', target: "_blank", rel: "noopener noreferrer", class: "fab fa-facebook-f" %>
    </div>
</section>
<div class="fullscreen-modal" id="loginModal">
    
    <div class="close"><i class="fas fa-times" onclick="showLoginModal()"></i></div>
    <div class="card">
    <%= form_for(:admin, as: Admin, url: session_path(Admin)) do |f| %>
        <h2>Login</h2>
        <div class="form-group ">
            <label for="">Email</label>
            <%= f.email_field :email, class: 'form-field', id: 'loginEmail', required: true  %>
        </div>
        <div class="form-group">
            <label for="">Passwort</label>
            <div class="right"><%= link_to "Passwort vergessen?", new_password_path(Admin) %></div>
            <%= f.password_field :password, class: 'form-field',id: 'loginPassword', required: true  %>
            <br>
        </div>
        <div class="form-group center">
            <%= f.submit 'Login', class: 'btn btn-green', id: "loginButton" %>
        </div>
    <% end %>
    </div>
</div>
<script>
    function showLoginModal() {
        $('#loginModal').toggle();
    }
</script>

app/views/landing/sign_up_next.html.erb
 
<div class="verification-canvas py-4 d-flex align-items-center justify-content-center register-page">
  <div class="container register-container">
    <!----------------<div class="text-center">
      <a href="#" class="register-logo d-inline-block"><%= image_tag ("logo.png") ,alt:"IMG"%></a>
    </div> ----->
    <div class="row">
      <div class="col-12">
          <!-------<h1 class="form-heading mb-5 pb-2">registrieren</h1> ------->
      <%= form_for(@admin, url: update_admin_details_path(v_id: @admin.vid_token)) do |f| %>

          <div class="form-main-canvas">
            <div class="form-group">
              <label for=""> Unternehmensname</label>
              <%= f.text_field :company_name, class: 'form-control', autocomplete: "off",required: true %>
            </div>

            <div class="form-group">
              <label for=""> Straße</label>

              <%= f.text_field :street, class: 'form-control', autocomplete: "off",required: true %>
            </div>  
            <div class="form-group form-group-postal">
              <label for=""> PLZ</label>
              <%= f.text_field :zipcode, class: 'form-control', autocomplete: "off",required: true %>
            </div>

            <div class="form-group">
              <label for=""> Stadt</label>
              <%= f.text_field :city, class: 'form-control', autocomplete: "off",required: true %>
            </div>

             <div class="form-group text-center pt-2 px-md-5">
              <%= f.submit 'Registrieren', class: 'btn btn-green' %>
            </div>
      <%end%>  
            
          </div>   
      </div>
    </div>
  </div>
</div>