config/routes.rb
Rails.application.routes.draw do
  devise_for :games
  devise_for :users
  devise_for :admins, controllers: { registrations: 'admins/registrations', sessions: 'admins/sessions', passwords: 'admins/passwords', confirmations: 'admins/confirmations', unlocks: 'admins/unlocks'}
  resource :cards
  resource :plans

  # root to: 'games#show'
  patch 'game_mobile_user/accept_user/:user_id', to: 'game_mobile_user#accept_user', as: 'accept_user'
  patch 'game_mobile_user/reject_user/:user_id', to: 'game_mobile_user#reject_user', as: 'reject_user'
 
###########
# Landing #
###########
  root 'landing#index'
  get 'admins/:admin_id/confirm', to: "landing#after_confirm", as: 'admin_after_confirm'
  get 'cookies', to: 'landing#accept_cookies', as: 'accept_cookies'
  get '/contact', to: 'landing#contact', as: 'contact'
  get 'product', to: 'landing#product', as: 'product'
  get 'datenschutz', to: 'landing#datenschutz', as: 'datenschutz'
  get 'impressum', to: 'landing#impressum', as: 'impressum'
  get 'blog', to: 'landing#blog', as: 'blog'
  get 'blog/:blog_id', to: 'landing#show_blog', as: 'show_blog'
	
  get 'landing/ended_game', to: 'landing#ended_game', as: 'landing_ended_game'

  get '/byebye', to: 'landing#byebye', as: 'byebye'
  # patch 'verification/verify_token' ,to: 'verification#verify_token' , as:'verify_token'
  get 'admins/register', to: 'landing#register', as: 'register'
  get 'admins/signup/:v_id', to: 'landing#signup' , as: 'edit_next_admin'
  patch 'admins/update_admin/:v_id', to: 'landing#update_admin', as: 'update_admin'
  patch 'admins/update_admin_details/:v_id', to: 'landing#update_admin_details', as: 'update_admin_details'

  get 'coaches/info', to: 'landing#coach', as: 'coach_info'
  # get '/verfication/:token' , to: 'verification#token' , as: 'verification_token'
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
########
# Game #
########

#################
# Admin Desktop #
#################

  get 'games/wait', to: 'game_desktop_admin#wait', as: 'gda_wait'
  get 'games/intro', to: 'game_desktop_admin#intro', as: 'gda_intro'
  get 'games/youtube_video', to: 'game_desktop_admin#youtube_video', as: 'gda_youtube'
  get 'games/choose', to: 'game_desktop_admin#choose', as: 'gda_choose'
  get 'games/turn', to: 'game_desktop_admin#turn', as: 'gda_turn'
  get 'games/error', to: 'game_desktop_admin#error', as: 'gea_turn'
  get 'video_testing', to: 'game_mobile_admin#video_testing'
  get 'games/play', to: 'game_desktop_admin#play', as: 'gda_play'
  get 'games/rate', to: 'game_desktop_admin#rate', as: 'gda_rate'
  get 'games/rating', to: 'game_desktop_admin#rating', as: 'gda_rating'
  get 'games/skip_rating', to: 'game_desktop_admin#skip_rating', as: 'gda_skip_rating'
  get 'games/bestlist', to: 'game_desktop_admin#bestlist', as: 'gda_bestlist'
  get 'games/ended', to: 'game_desktop_admin#ended', as: 'gda_ended'
  get 'games/ended_game', to: 'game_desktop_admin#ended_game', as: 'gda_ended_game'
  get 'games/replay', to: 'game_desktop_admin#replay', as: 'gda_replay'
    
  get 'games/after_rating', to: 'game_desktop_admin#after_rating', as: 'gda_after_rating'
  get 'games/video_uploaded_status', to: 'game_desktop_admin#video_uploaded_status', as: 'gda_video_uploaded_status'
  

################
# Admin Mobile #
################

  
  get 'mobile/admins/:password', to: 'game_mobile_admin#new', as: 'gma_start'
  post 'mobile/admins/:password', to: 'game_mobile_admin#create'
  get 'mobile/admin/avatar', to: 'game_mobile_admin#new_avatar', as: 'gma_new_avatar'
  post 'mobile/admin/avatar', to: 'game_mobile_admin#create_avatar'
  get 'mobile/admin/new_turn', to: 'game_mobile_admin#new_turn', as: 'gma_new_turn'
  post 'mobile/admin/new_turn', to: 'game_mobile_admin#create_turn'
    
  get 'mobile/admin/wait', to: 'game_mobile_admin#wait', as: 'gma_wait'
  post 'mobile/admin/after_wait', to: 'game_mobile_admin#after_wait', as: 'gma_after_wait'
  post 'mobile/admin/before_intro', to: 'game_mobile_admin#before_intro', as: 'gma_before_intro'
  get 'mobile/admin/intro', to: 'game_mobile_admin#intro', as: 'gma_intro'
  get 'mobile/admin/select_user', to: 'game_mobile_admin#choose_rating_user', as: 'gma_choose_rating_user'
  get 'mobile/admin/youtube_video', to: 'game_mobile_admin#youtube_video', as: 'gma_youtube'
  get 'mobile/admin/error', to: 'game_mobile_admin#error', as: 'gea_mobile'
  get 'mobile/admin/choose', to: 'game_mobile_admin#choose', as: 'gma_choose'
  get 'mobile/admin/choosen/:turn_id', to: 'game_mobile_admin#choosen', as: 'gma_choosen'
  get 'mobile/admin/turn', to: 'game_mobile_admin#turn', as: 'gma_turn'
  get 'mobile/admin/play', to: 'game_mobile_admin#play', as: 'gma_play'
  get 'mobile/admin/react', to: 'game_mobile_admin#react', as: 'gma_react'
  post 'mobile/admin/upload', to: 'game_mobile_admin#save_video', as: 'gpitchsave_play'
  get 'mobile/admin/video_cancel', to: 'game_mobile_admin#video_cancel',as: 'cancel_video_uploading'
  get 'mobile/admin/rate', to: 'game_mobile_admin#rate', as: 'gma_rate'
  get 'mobile/admin/rated', to: 'game_mobile_admin#rated', as: 'gma_rated'
  get 'mobile/admin/rating', to: 'game_mobile_admin#rating', as: 'gma_rating'
  get 'mobile/admin/skip_rating', to: 'game_mobile_admin#skip_rating', as: 'gma_skip_rating'
  get 'mobile/admin/bestlist', to: 'game_mobile_admin#bestlist', as: 'gma_bestlist'
  get 'mobile/admin/replay', to: 'game_mobile_admin#replay', as: 'gma_replay'
  get 'mobile/admin/ended', to: 'game_mobile_admin#ended', as: 'gma_ended'
  get 'mobile/admin/ended_game', to: 'game_mobile_admin#ended_game', as: 'gma_ended_game'
  get 'mobile/admin/after_rating', to: 'game_mobile_admin#after_rating', as: 'gma_after_rating'
  post 'mobile/admin/update_video_status', to: 'game_mobile_admin#update_video_status', as: 'gma_update_video_status'

    
###############
# User Mobile #
###############
    
  get 'mobile/user/game', to: 'game_mobile_user#new', as: 'gmu_password'
  post 'mobile/user/game', to: 'game_mobile_user#create'

  get 'mobile/user/name', to: 'game_mobile_user#new_name', as: 'gmu_new_name'
  post 'mobile/user/name', to: 'game_mobile_user#create_name'
    
  get 'mobile/user/company', to: 'game_mobile_user#new_company', as: 'gmu_new_company'
  post 'mobile/user/company', to: 'game_mobile_user#create_company'
    
  get 'mobile/user/avatar', to: 'game_mobile_user#new_avatar', as: 'gmu_new_avatar'
  post 'mobile/user/avatar', to: 'game_mobile_user#create_avatar'
    
  get 'mobile/user/game/new_turn', to: 'game_mobile_user#new_turn', as: 'gmu_new_turn'
  post 'mobile/user/game/new_turn', to: 'game_mobile_user#create_turn'
  get 'mobile/user/game/vidoe_uploading', to: 'game_mobile_user#video_uploading', as: 'gmu_video_check'
  get 'mobile/user/game/wait', to: 'game_mobile_user#wait', as: 'gmu_wait'
  get 'mobile/user/game/intro', to: 'game_mobile_user#intro', as: 'gmu_intro'
  get 'mobile/user/game/choose', to: 'game_mobile_user#choose', as: 'gmu_choose'
  get 'mobile/user/game/choosen/:turn_id', to: 'game_mobile_user#choosen', as: 'gmu_choosen'
  get 'mobile/user/game/turn', to: 'game_mobile_user#turn', as: 'gmu_turn'
  get 'mobile/user/game/play', to: 'game_mobile_user#play', as: 'gmu_play'
  get 'mobile/user/game/react', to: 'game_mobile_user#react', as: 'gmu_react'
  get 'mobile/user/game/rate', to: 'game_mobile_user#rate', as: 'gmu_rate'
  get 'mobile/user/game/rated', to: 'game_mobile_user#rated', as: 'gmu_rated'
  get 'mobile/user/game/rating', to: 'game_mobile_user#rating', as: 'gmu_rating'
  get 'mobile/user/game/skip_rating', to: 'game_mobile_user#skip_rating', as: 'gmu_skip_rating'
  get 'mobile/user/game/bestlist', to: 'game_mobile_user#bestlist', as: 'gmu_bestlist'
  get 'mobile/user/game/replay', to: 'game_mobile_user#replay', as: 'gmu_replay'
  get 'mobile/user/game/ended', to: 'game_mobile_user#ended', as: 'gmu_ended'
  get 'mobile/user/game/ended_game', to: 'game_mobile_user#ended_game', as: 'gmu_ended_game'
	
############
# Vertrieb #
############
	
  get '/vertrieb', to: 'vertrieb#new', as: 'vertrieb'
  post 'vertrieb/new', to: 'vertrieb#create', as: 'new_vertrieb'
  post 'vertrieb/login', to: 'vertrieb#login', as: 'login_vertrieb'
 
  get 'vertrieb/start', to: 'vertrieb#start', as: 'start_vertrieb'
  get 'vertrieb/proceed', to: 'vertrieb#proceed', as: 'proceed_vertrieb'
	
  get "vertrieb/game_wait", to: "vertrieb#game_wait", as: 'game_wait_vertrieb'
  get 'vertrieb/game_choose', to: 'vertrieb#game_choose', as: 'game_choose_vertrieb'
  get 'vertrieb/game_turn', to: 'vertrieb#game_turn', as: 'game_turn_vertrieb'
  get 'vertrieb/game_play', to: 'vertrieb#game_play', as: 'game_play_vertrieb'
  get 'vertrieb/game_rate', to: 'vertrieb#game_rate', as: 'game_rate_vertrieb'
  get 'vertrieb/game_rated', to: "vertrieb#game_rated", as: 'game_rated_vertrieb'
  get 'vertrieb/game_bestlist', to: 'vertrieb#game_bestlist', as: 'game_bestlist_vertrieb'
	
  get 'vertrieb/dash_customize', to: 'vertrieb#dash_customize', as: 'dash_customize_vertrieb'
  get 'vertrieb/dash_lets_pitch', to: 'vertrieb#dash_lets_pitch', as: 'dash_lets_pitch_vertrieb'
  get 'vertrieb/dash_lets_pitch2', to: 'vertrieb#dash_lets_pitch2', as: 'dash_lets_pitch2_vertrieb'
  get 'vertrieb/dash_user_stats', to: 'vertrieb#dash_user_stats', as: 'dash_user_stats_vertrieb'
  get 'vertrieb/dash_users', to: 'vertrieb#dash_users', as: 'dash_users_vertrieb'
  get 'vertrieb/dash_videoanalyse', to: 'vertrieb#dash_videoanalyse', as: 'dash_videoanalyse_vertrieb'
	
  get 'vertrieb/ended', to: 'vertrieb#ended', as: 'ended_vertrieb'
    
####################################################################################
#############
# Dashboard #
#############

##############
# Backoffice #
##############
  
  get 'backoffice', to: 'backoffice#index', as: 'backoffice'
	
  get 'backoffice/admins', to: 'backoffice#admins', as: 'backoffice_admins'
  get 'backoffice/admins/:admin_id', to: 'backoffice#admin', as: 'backoffice_admin'

app/views/game_mobile_user/_toggle_for_rate.html.erb
<div class="switch-box switch-box-vt" id="switch">
	<label class="switch">
		<input type="checkbox" id="start" value="rate" name="play">
		<span class="slider round"></span>
	</label>
	<p class="text-for-switch nunito-regular" id=''>Ich möchte selbst nicht pitchen,<br> sondern nur bewerten</p>
</div>

app/views/game_mobile_user/bestlist.html.erb
<%= render partial: 'game_mobile_admin/header' , locals: {can: false}%>
<div class="head">
    <h1 class="nunito-bold">Tolle Runde!</h1>
</div>
<div class="middle">
    <div class="circle" id="ges">
        <%= image_tag @user.avatar.quad.url, class: 'mid-img' %>
    </div>
    <%= image_tag 'game/polygon.png', class: 'pol' %>
    <div class="rating" id='ges_text'>?</div>
</div>
<div class="bottom links">
    <a href="<%= gmu_ended_game_path %>" class="pol-bg" style="display: inline;" data-confirm="Bist du sicher, dass du nicht weiterpitchen möchtest?"><i class="fas fa-times"></i></a>
    <a type="button" class="pol-bg" style="display: inline;" onclick="showModal()"><i class="fas fa-share-alt"></i></a>
</div>
<!-- Modal -->
<% if @turn_rating %>
    <div id="shareModal">
        <button type="button" class="close modal-close" id="close" onclick="closeModal()" aria-label="Close" style="transform: rotateZ(45deg);">+</button>
        <div class="header nunito-bold">
            - Teile dein Ergebnis -
        </div>
        <div class="links1">
            <%= social_share_button_tag('Ich habe ' + @word.name + ' gepitcht. Mein Pitchscore war ' + (@turn_rating.value/ 10.0).to_s + ' ! Wie gut bist du?', :url => "https://www.peterpitch.com", desc: 'Mein Pitchscore ist ' + (@turn_rating.value/ 10.0).to_s + ' ! Wie gut bist du?', :allow_sites => %w(twitter linkedin Xing)) %>
        </div>
        <div class="links2">
            <%= social_share_button_tag('Ich habe ' + @word.name + ' gepitcht. Mein Pitchscore war ' + (@turn_rating.value/ 10.0).to_s + ' ! Wie gut bist du? https://www.peterpitch.com', :url => "https://www.peterpitch.com", desc: 'Mein Pitchscore ist ' + (@turn_rating.value/ 10.0).to_s + ' ! Wie gut bist du?', :allow_sites => %w(whatsapp_app facebook)) %>
        </div>
    </div>

    <script>
	checkOrientation();
 	window.addEventListener('resize', checkOrientation);
    setTimeout(function() {
      ratecircle('#ges', 'ges_text', <%= @turn_rating.value / 100.0 %>);
      $('.mid-img').addClass('pulse');
    }, 1500);
    function showModal() {
        $('#shareModal').show();
    }
    function closeModal() {
        $('#shareModal').hide();
    }
    </script>
<% end %>

app/views/game_mobile_user/choose.html.erb
<%= render partial: 'game_mobile_admin/header' , locals: {can: false}%>
<div class="head">
    <h1 class="nunito-bold">Jetzt wählen!</h1>
</div>
<div class="middle">
    <%= image_tag @turn1.findUser.avatar.quad.url, class: 'mid-img-left blue' %>
    <%= image_tag @turn2.findUser.avatar.quad.url, class: 'mid-img-right blue' %>
    <%= link_to '', gmu_choosen_path(@turn1),class: 'mid-img-left' %>
    <%= link_to '', gmu_choosen_path(@turn2), class: 'mid-img-right' %>
</div>
<div class="bottom">
</div>
<script>
	checkOrientation();
 	window.addEventListener('resize', checkOrientation);
</script>

app/views/game_mobile_user/choosen.html.erb
<%= render partial: 'game_mobile_admin/header' , locals: {can: false} %>
<div class="head">
    <h1 class="nunito-bold">Du hast für <%= @turn.findUser.fname %> gestimmt!</h1>
</div>
<div class="middle">
    <%= image_tag @turn.findUser.avatar.quad.url, class: 'mid-img green pulse' %>
</div>
<div class="bottom">
</div>
<script>
	checkOrientation();
 	window.addEventListener('resize', checkOrientation);
</script>

app/views/game_mobile_user/end_pitch.html.erb
<a href="<%= root_path %>">Go to Dash board<a>

app/views/game_mobile_user/new.html.erb
<%= render partial: 'game_mobile_admin/header' , locals: {can: false}%>
<div class="body-section">
<div class="head nunito-bold">
    <h1>Wie ist deine E-Mail?</h1>
</div>
<%= form_for(:user, url: gmu_password_path, html: {autocomplete: 'off'}) do |f| %>
<div class="middle-form">
    <div class="row">
        <% if flash.count != 0 %>
        <div class="col-12 red nunito-regular">
            <%= f.email_field :email, placeholder: 'E-Mail', class: 'form-field' %>
        </div>
        <% else %>
        <div class="col-12 nunito-regular">
            <%= f.email_field :email, placeholder: 'E-Mail', class: 'form-field' %>
        </div>
        <% end %>
    </div>
</div>
<div class="bottom">
    <%= f.submit 'weiter!', class: 'link pulse nunito-regular' %>
</div>
<% end %>
</div>
<script>
window.removeEventListener('resize', checkOrientation);
</script>

app/views/game_mobile_user/new_avatar.html.erb
<%= render partial: 'game_mobile_admin/header' , locals: {can: false}%>
<% if @user.avatar? %>
<div class="head">
    <h1 class="nunito-bold">Wow!</h1>
    <h3 class="nunito-regular">Drücke auf "weiter" oder auf das <br> Bild für einen neuen Versuch!</h3>
</div>
<% else %>
<div class="head">
    <h1 class="nunito-bold">Bild hinzufügen!</h1>
    <h3 class="nunito-regular">Drücke das Plus, um ein Foto zu machen oder ein bestehendes Bild von dir hochzuladen.</h3>
</div>
<% end %>
<div class="middle">
    <%= form_for(:user, url: gmu_new_avatar_path) do |f| %>
    <% if @user.avatar? %>
    <label for="user_avatar" id="user_pic">
        <%= image_tag @user.avatar.quad.url, class: 'mid-img blue' %>
    </label>
        
       
        <div class="add">
          <i class="fas fa-check-circle"></i>
        </div>

        
      <% else %>
        <label for="user_avatar" id='user_pic'>
          <%= image_tag 'game/plus.png', class: 'mid-img pulse' %>
        </label>
      <% end %>
      <%= f.file_field :avatar, onchange: 'auto()' %>
      <%= f.submit '', style: 'display:none'%>
    <% end %>
  </div>
  <% if @user.avatar? %>
    <%= form_for(:user, url: gmu_new_turn_path, method: 'get') do |f| %>

    <div class="bottom bottom-play">
      <%= render partial: 'toggle_for_rate' %>
    </div>
    <div class="bottom">
    	<%= f.submit 'weiter!', class: 'link pulse nunito-regular' %>
    </div>
    <% end %>
<% end %>

<script>
function auto() {
    $('form').submit();
    $("form").replaceWith("<div class='spinner spinner1'></div>");
}
</script>
<script>
	checkOrientation();
 	window.addEventListener('resize', checkOrientation);
</script>

app/views/game_mobile_user/new_company.html.erb
<%= render partial: 'game_mobile_admin/header' , locals: {can: false}%>
<div class="head">
    <h1 class="nunito-bold">In welcher Firma <br> arbeitest du?</h1>
</div>
<%= form_for(:user, url: gmu_new_company_path, html: {autocomplete: 'off'}) do |f| %>
<div class="middle-form">
    <div class="row">
        <div class="col-12">
            <%= f.text_field :company_name, placeholder: 'Firma', class: 'form-field nunito-regular' %>
        </div>
    </div>
</div>
<div class="bottom">
    <%= f.submit 'weiter!', class: 'link pulse nunito-regular' %>
</div>
<% end %>
<script>
	window.removeEventListener('resize', checkOrientation);
</script>

app/views/game_mobile_user/new_password.html.erb
<%= render partial: 'game_mobile_admin/header' , locals: {can: false}%>
<div class="head">
    <h1 class="nunito-bold">Dein Passwort?</h1>
</div>
<%= form_for(:user, url: gmu_new_password_path, html: {autocomplete: 'off'}) do |f| %>
<div class="middle-form">
    <div class="row">
        <div class="col-12">
            <%= f.password_field :password, placeholder: 'Passwort festlegen', class: 'form-field nunito-regular', onchange: 'enterPassword()' %>
        </div>
    </div>
</div>
<div class="bottom">
    <%= link_to 'weiter!', '', class: 'link nunito-regular', id: 'fake' %>
    <%= f.submit 'weiter!', class: 'link pulse nunito-regular', id: 'summit', style: 'display: none' %>
</div>
<% end %>



<script>
    function enterPassword() {
        $('#fake').hide();
        $('#summit').show();
    }
	window.removeEventListener('resize', checkOrientation);
</script>

app/views/game_mobile_user/new_turn.html.erb
<%= render partial: 'game_mobile_admin/header' , locals: {can: false}%>
<div class="head">
    <h1>Hi, <%= @user.fname %></h1>
</div>
<%= form_for(:turn, url: gmu_new_turn_path) do |f| %>
<div class="middle">
    <div class="row">
        <%= f.radio_button :play, true, onchange: "myFunction()" %>
        <div class="col-12">
            <label for="turn_play_true" class="custom-text">Ich pitche und bewerte!</label>
        </div>
    </div>
    <div class="row">
        <div class="col-12">-oder-</div>
    </div>
    <div class="row">
        <%= f.radio_button :play, false, onchange: "myFunction()" %>
        <div class="col-12">
            <label for="turn_play_false" class="custom-text">Ich möchte nur bewerten</label>
        </div>
    </div>
</div>
<div class="bottom">
    <%= link_to "weiter!", '', class: 'link nunito-regular', id: 'fake' %>
    <%= f.submit "weiter!", class: 'link pulse nunito-regular', id: 'summit', style: 'display: none' %>
</div>
<% end %>


<script>
    function myFunction() {
        $('#fake').hide();
        $('#summit').show();
    }
</script>
<script>
	checkOrientation();
 	window.addEventListener('resize', checkOrientation);
</script>

app/views/game_mobile_user/rate.html.erb
<%= render partial: 'game_mobile_admin/header' , locals: {can: false}%>
<div class="head">
    <h1 class="nunito-bold">Jetzt <%= @cur_user.fname %> bewerten!</h1>
</div>
<%
    if @custom_rating.rating_criteria.count == 1
        @top = 65
    elsif @custom_rating.rating_criteria.count == 2
        @top = 60
    elsif @custom_rating.rating_criteria.count == 3
        @top = 55
    else
        @top = 50
    end
%>
<%= form_for(:rating, url: new_user_rating_criteria_path(@turn)) do |f| %>
    <div class="middle" style="top: calc(<%= @top %>% - 350px);">
        <% @custom_rating.rating_criteria.each_with_index do |rating, index| %>
            <div class="row">
                <label for="" class="ellipsis-text nunito-bold"><%= rating.name.titleize %></label><div class="output" id="val<%= index+1 %>"></div>
                <%= f.range_field rating.name, min: 0, max: 100, id: "slider#{index+1}" %>
            </div>  
        <% end %>
    </div>
<!-- <div class="middle">
    <div class="row">
        <%= f.label 'Spontanität: ', class: 'nunito-bold' %> <div class="output" id="val1"></div>
        <%= f.range_field :spontan, min: 0, max: 100, id: 'slider1' %>
    </div>
    <div class="row">
        <%= f.label 'Kreativität: ', class: 'nunito-bold' %> <div class="output" id="val2"></div>
        <%= f.range_field :creative, min: 0, max: 100, id: 'slider2' %>
    </div>
    <div class="row">
        <%= f.label 'Körpersprache: ', class: 'nunito-bold' %> <div class="output" id="val3"></div>
        <%= f.range_field :body, min: 0, max: 100, id: 'slider3' %>
    </div>
    <div class="row">
        <%= f.label 'Rhetorik: ', class: 'nunito-bold' %> <div class="output" id="val4"></div>
        <%= f.range_field :rhetoric, min: 0, max: 100, id: 'slider4' %>
    </div>
</div> -->
<div class="bottom">
    <%= f.submit 'weiter!', class: 'link nunito-regular' %>
</div>
<% end %>

<script>
$('input[type="range"]').rangeslider({

    // Feature detection the default is `true`.
    // Set this to `false` if you want to use
    // the polyfill also in Browsers which support
    // the native <input type="range"> element.
    polyfill: false,

    // Default CSS classes
    rangeClass: 'rangeslider',
    disabledClass: 'rangeslider--disabled',
    horizontalClass: 'rangeslider--horizontal',
    verticalClass: 'rangeslider--vertical',
    fillClass: 'rangeslider__fill',
    handleClass: 'rangeslider__handle',

    // Callback function
    onInit: function() {},

    // Callback function
    onSlide: function(position, value) {},

    // Callback function
    onSlideEnd: function(position, value) {}
});

    var ratings_count = <%= @custom_rating.rating_criteria.count %>;
    if (ratings_count >= 1) {
        var slider1 = document.getElementById("slider1");
        var output1 = document.getElementById("val1");
        output1.innerHTML = parseFloat(slider1.value / 10.0).toFixed(1);
        slider1.oninput = function() {
            output1.innerHTML = parseFloat(this.value / 10.0).toFixed(1);
        }
    }
    if (ratings_count >= 2) {
        var slider2 = document.getElementById("slider2");
        var output2 = document.getElementById("val2");
        output2.innerHTML = parseFloat(slider2.value / 10.0).toFixed(1);
        slider2.oninput = function() {
            output2.innerHTML = parseFloat(this.value / 10.0).toFixed(1);
        }
    }
    if (ratings_count >= 3) {
        var slider3 = document.getElementById("slider3");
        var output3 = document.getElementById("val3");
        output3.innerHTML = parseFloat(slider3.value / 10.0).toFixed(1);
        slider3.oninput = function() {
            output3.innerHTML = parseFloat(this.value / 10.0).toFixed(1);
        }
    }
    if (ratings_count >= 4) {
        var slider4 = document.getElementById("slider4");
        var output4 = document.getElementById("val4");
        output4.innerHTML = parseFloat(slider4.value / 10.0).toFixed(1);
        slider4.oninput = function() {
            output4.innerHTML = parseFloat(this.value / 10.0).toFixed(1);
        }
    }
</script>
<script>
	checkOrientation();
 	window.addEventListener('resize', checkOrientation);
</script>

app/views/game_mobile_user/rating.html.erb
<%= render partial: 'game_mobile_admin/header' , locals: {can: false}%>
<div class="head">
    <h1 class="nunito-bold">Hier ist die Bewertung!</h1>
</div>
<div class="middle">
    <%= image_tag @cur_user.avatar.quad.url || 'defaults/wolf.jpg', class: 'mid-img green pulse' %>
</div>
<script>
	checkOrientation();
 	window.addEventListener('resize', checkOrientation);
</script>

app/views/game_mobile_user/turn.html.erb
<%= render partial: 'game_mobile_admin/header' , locals: {can: false}%>
<div class="head">
    <h1>
      <% if @user == @cur_user %>
        <h1 class="nunito-bold"><%= @cur_user.fname %>, du bist dran!</h1>
      <% else %>
        <h1 class="nunito-bold"><%= @cur_user.fname %> ist dran!</h1>
      <% end %>
    </h1>
</div>
<div class="middle">
    <%= image_tag @cur_user.avatar.quad.url, class: 'mid-img green pulse' %>
</div>
<script>
	checkOrientation();
 	window.addEventListener('resize', checkOrientation);
</script>

app/views/game_mobile_user/wait.html.erb
<%= render partial: 'game_mobile_admin/header' , locals: {can: false}%>
<div class="head">
    <h1 class="nunito-bold">PITCH BEIGETRETEN!</h1>
</div>
<div class="middle">
    <%if @user.avatar.quad.url%>
        <%= image_tag @user.avatar.quad.url, class: 'mid-img green pulse' %>
    <%else%>
        <%= image_tag 'logo.png', class: 'mid-img green pulse' %>
    <%end%>
</div>

<div class="bottom nunito-regular">
    Gleich geht's los...
</div>
<script>
	checkOrientation();
 	window.addEventListener('resize', checkOrientation);
</script>