config/routes.rb
  get 'mobile/user/avatar', to: 'game_mobile_user#new_avatar', as: 'gmu_new_avatar'
  post 'mobile/user/avatar', to: 'game_mobile_user#create_avatar'
    
  get 'mobile/user/game/new_turn', to: 'game_mobile_user#new_turn', as: 'gmu_new_turn'
  post 'mobile/user/game/new_turn', to: 'game_mobile_user#create_turn'
  get 'mobile/user/game/vidoe_uploading', to: 'game_mobile_user#video_uploading', as: 'gmu_video_check'
  get 'mobile/user/game/wait', to: 'game_mobile_user#wait', as: 'gmu_wait'
  get 'mobile/user/game/intro', to: 'game_mobile_user#intro', as: 'gmu_intro'
  get 'mobile/user/game/choose', to: 'game_mobile_user#choose', as: 'gmu_choose'
  get 'mobile/user/game/choosen/:turn_id', to: 'game_mobile_user#choosen', as: 'gmu_choosen'
  get 'mobile/user/game/turn', to: 'game_mobile_user#turn', as: 'gmu_turn'
  get 'mobile/user/game/play', to: 'game_mobile_user#play', as: 'gmu_play'
  get 'mobile/user/game/react', to: 'game_mobile_user#react', as: 'gmu_react'
  get 'mobile/user/game/rate', to: 'game_mobile_user#rate', as: 'gmu_rate'
  get 'mobile/user/game/rated', to: 'game_mobile_user#rated', as: 'gmu_rated'
  get 'mobile/user/game/rating', to: 'game_mobile_user#rating', as: 'gmu_rating'
  get 'mobile/user/game/skip_rating', to: 'game_mobile_user#skip_rating', as: 'gmu_skip_rating'
  get 'mobile/user/game/bestlist', to: 'game_mobile_user#bestlist', as: 'gmu_bestlist'
  get 'mobile/user/game/replay', to: 'game_mobile_user#replay', as: 'gmu_replay'
  get 'mobile/user/game/ended', to: 'game_mobile_user#ended', as: 'gmu_ended'
  get 'mobile/user/game/ended_game', to: 'game_mobile_user#ended_game', as: 'gmu_ended_game'
	
############
# Vertrieb #
############
	
  get '/vertrieb', to: 'vertrieb#new', as: 'vertrieb'
  post 'vertrieb/new', to: 'vertrieb#create', as: 'new_vertrieb'
  post 'vertrieb/login', to: 'vertrieb#login', as: 'login_vertrieb'
 
  get 'vertrieb/start', to: 'vertrieb#start', as: 'start_vertrieb'
  get 'vertrieb/proceed', to: 'vertrieb#proceed', as: 'proceed_vertrieb'
	
  get "vertrieb/game_wait", to: "vertrieb#game_wait", as: 'game_wait_vertrieb'
  get 'vertrieb/game_choose', to: 'vertrieb#game_choose', as: 'game_choose_vertrieb'
  get 'vertrieb/game_turn', to: 'vertrieb#game_turn', as: 'game_turn_vertrieb'
  get 'vertrieb/game_play', to: 'vertrieb#game_play', as: 'game_play_vertrieb'
  get 'vertrieb/game_rate', to: 'vertrieb#game_rate', as: 'game_rate_vertrieb'
  get 'vertrieb/game_rated', to: "vertrieb#game_rated", as: 'game_rated_vertrieb'
  get 'vertrieb/game_bestlist', to: 'vertrieb#game_bestlist', as: 'game_bestlist_vertrieb'
	
  get 'vertrieb/dash_customize', to: 'vertrieb#dash_customize', as: 'dash_customize_vertrieb'
  get 'vertrieb/dash_lets_pitch', to: 'vertrieb#dash_lets_pitch', as: 'dash_lets_pitch_vertrieb'
  get 'vertrieb/dash_lets_pitch2', to: 'vertrieb#dash_lets_pitch2', as: 'dash_lets_pitch2_vertrieb'
  get 'vertrieb/dash_user_stats', to: 'vertrieb#dash_user_stats', as: 'dash_user_stats_vertrieb'
  get 'vertrieb/dash_users', to: 'vertrieb#dash_users', as: 'dash_users_vertrieb'
  get 'vertrieb/dash_videoanalyse', to: 'vertrieb#dash_videoanalyse', as: 'dash_videoanalyse_vertrieb'
	
  get 'vertrieb/ended', to: 'vertrieb#ended', as: 'ended_vertrieb'
    
####################################################################################
#############
# Dashboard #
#############

##############
# Backoffice #
##############
  
  get 'backoffice', to: 'backoffice#index', as: 'backoffice'
	
  get 'backoffice/admins', to: 'backoffice#admins', as: 'backoffice_admins'
  get 'backoffice/admins/:admin_id', to: 'backoffice#admin', as: 'backoffice_admin'
  get 'backoffice/admins/:admin_id/teams', to: 'backoffice#teams', as: 'backoffice_teams'
  get 'backoffice/admins/:admin_id/teams/:team_id', to: 'backoffice#team', as: 'backoffice_team'
  get 'backoffice/admins/:admin_id/users', to: 'backoffice#users', as: 'backoffice_users'
  get 'backoffice/admins/:admin_id/users/:user_id', to: 'backoffice#user', as: 'backoffice_user'
  get 'backoffice/admins/:admin_id/games', to: 'backoffice#games', as: 'backoffice_games'
  get 'backoffice/admins/:admin_id/games/:game_id', to: 'backoffice#game', as: 'backoffice_game'
  get 'backoffice/admins/:admin_id/words', to: 'backoffice#words', as: 'backoffice_words'
  get 'backoffice/admins/:admin_id/words/:basket_id', to: 'backoffice#word', as: 'backoffice_word'
  get 'backoffice/words', to: 'backoffice#words', as: 'backoffice_words_noadmin'
  get 'backoffice/words/:basket_id', to: 'backoffice#word', as: 'backoffice_word_noadmin'
  get 'backoffice/admins/:admin_id/objections', to: 'backoffice#objections', as: 'backoffice_objections'
  get 'backoffice/admins/:admin_id/objections/:basket_id', to: 'backoffice#objection', as: 'backoffice_objection'
  get 'backoffice/objections', to: 'backoffice#objections', as: 'backoffice_objections_noadmin'
  get 'backoffice/objections/:basket_id', to: 'backoffice#objection', as: 'backoffice_objection_noadmin'
	
  get 'backoffice/roots', to: 'backoffice#roots', as: 'backoffice_roots'
  get 'backoffice/roots/:root_id', to: 'backoffice#root', as: 'backoffice_root'
  get 'backoffice/sales', to: 'backoffice#sales', as: 'backoffice_sales'
  get 'backoffice/sales/:vertrieb_id/sale_pictures', to: 'backoffice#sale_pictures', as: 'backoffice_sale_pictures'
  get 'backoffice/blogs', to: 'backoffice#blogs', as: 'backoffice_blogs'
  get 'backoffice/blogs/:blog_id', to: 'backoffice#blog', as: 'backoffice_blog'
  ##############
  # CRUD Admin #
  ##############
  post 'backoffice/admins/new', to: 'backoffice#new_admin', as: 'backoffice_new_admin'
  get 'backoffice/admins/:admin_id/activate', to: 'backoffice#activate_admin', as: 'backoffice_activate_admin'
  post 'backoffice/admins/:admin_id/edit', to: 'backoffice#edit_admin', as: 'backoffice_edit_admin'
  put 'backoffice/admins/:admin_id/update_avatar', to: 'backoffice#update_admin_avatar', as: 'backoffice_update_admin_avatar'
  put 'backoffice/admins/:admin_id/update_logo', to: 'backoffice#update_admin_logo', as: 'backoffice_update_admin_logo'
  get 'backoffice/admins/:admin_id/destroy', to: 'backoffice#destroy_admin', as: 'backoffice_destroy_admin'
  #############
  # CRUD Team #
  #############
  post 'backoffice/admins/:admin_id/teams/new', to: 'backoffice#new_team', as: 'backoffice_new_team'
  post 'backoffice/teams/:team_id/edit', to: 'backoffice#edit_team', as: 'backoffice_edit_team'
  get 'backoffice/teams/:team_id/destroy', to: 'backoffice#destroy_team', as: "backoffice_destroy_team"
  #############
  # CRUD User #
  #############
  post 'backoffice/admins/:admin_id/users/new', to: 'backoffice#new_user', as: 'backoffice_new_user'
  post 'backoffice/users/:user_id/edit', to: 'backoffice#edit_user', as: 'backoffice_edit_user'
  put 'backoffice/users/:user_id/update_avatar', to: 'backoffice#update_user_avatar', as: 'backoffice_update_user_avatar'
  get 'backoffice/users/:user_id/destroy', to: 'backoffice#destroy_user', as: 'backoffice_destroy_user'
  #############
  # CRUD Game #
  #############
  post 'backoffice/games/new',to: 'backoffice#new_game', as: 'backoffice_new_game'
  post 'backoffice/games/:game_id/edit',to: 'backoffice#edit_game', as: 'backoffice_edit_game'
  get 'backoffice/games/:game_id/destroy',to: 'backoffice#destroy_game', as: 'backoffice_destroy_game'
  #############
  # CRUD Turn #
  #############
  get 'backoffice/turns/:turn_id/destroy', to: "backoffice#destroy_turn", as: "backoffice_destroy_turn"
  ###############
  # CRUD Rating #
  ###############
  post 'ratings/:turn_id/edit', to: 'backoffice#update_rating', as: 'backoffice_edit_rating'
  #############
  # CRUD ROOT #
  #############
  post 'backoffice/roots/new', to: 'backoffice#new_root', as: 'backoffice_new_root'
  post 'backoffice/roots/:root_id/edit', to: 'backoffice#edit_root', as: 'backoffice_edit_root'
  put 'backoffice/roots/:root_id/update_avatar', to: "backoffice#update_root_avatar", as: "backoffice_update_root_avatar"
  get 'backoffice/roots/:root_id/destroy', to: 'backoffice#destroy_root', as: 'backoffice_destroy_root'
  #################
  # CRUD Vertrieb #
  #################
  put 'backoffice/sales/:vertrieb_id/update_avatar', to: 'backoffice#update_vertrieb_avatar', as: 'update_vertrieb_avatar'
  put 'backoffice/sales/:vertrieb_id/update_logo', to: 'backoffice#update_vertrieb_logo', as: 'update_vertrieb_logo'
  #############
  # CRUD Blog #
  #############
  post 'backoffice/blogs/new', to: 'backoffice#new_blog', as: "backoffice_new_blog"
  post 'backoffice/blogs/:blog_id/edit', to: 'backoffice#edit_blog', as: "backoffice_edit_blog"
  put 'backoffice/blogs/:blog_id/update_image', to: 'backoffice#update_blog_image', as: 'backoffice_update_blog_image'
  get 'backoffice/blogs/:blog_id/destroy', to: 'backoffice#destroy_blog', as: 'backoffice_destroy_blog'
  post 'backoffice/blogs/:blog_id/paragraphs/new', to: 'backoffice#new_blog_paragraph', as: 'backoffice_new_blog_paragraph'
  post 'backoffice/blog_paragraphs/:blog_paragraph_id/edit', to: "backoffice#edit_blog_paragraph", as: "backoffice_edit_blog_paragraph"
  get 'backoffice/blog_paragraphs/:blog_paragraph_id/destroy', to: 'backoffice#destroy_blog_paragraph', as: 'backoffice_destroy_blog_paragraph'

########
# User #
########
	
	get 'user/dash/stats', to: 'dash_user#stats', as: 'dash_user_stats'
	get 'user/dash/videos', to: 'dash_user#videos', as: "dash_user_videos"
	get 'user/dash/videos/:turn_id/', to: 'dash_user#video', as: "dash_user_video"
	post 'user/dash/comments/:comment_id/replies/new', to: 'dash_user#create_replies', as: 'dash_user_new_reply'
	get 'user/dash/account', to: 'dash_user#account', as: 'dash_user_account'
	post 'user/dash/edit', to: 'dash_user#edit_user', as: 'dash_user_edit'
	put 'user/dash/avatar', to: 'dash_user#update_avatar', as: 'dash_user_update_avatar'
#########
# Admin #
#########

    get 'admin/verification/:token', to: 'dash_admin#verification', as: 'dash_admin_verfication'

app/views/backoffice/blog.html.erb
<h1>Blog Eintrag</h1>
<div class="row">
	<div class="card">
		<h3>Bild</h3>
		<%= form_for(:blog, url: backoffice_edit_blog_path(@blog)) do |f| %>
		<div class="image">
			<label for="blog_image">
				<%= image_tag @blog.image? ? @blog.image.url : '', id: 'blogIMG' %>
			</label>
			<%= f.file_field :image %>
		</div>
		<% end %>
	</div>
	
	<div class="card">
		<h3>Blog - <%= @blog.created_at.strftime('%d.%m.%Y') %></h3>
		<%= form_for(:blog, url: backoffice_edit_blog_path(@blog)) do |f| %>
		<table>
			<tr>
				<th>Title</th>
				<td><%= f.text_field :title, class: 'form-field' %></td>
			</tr>
		</table>
		<%= f.text_area :text, class: 'form-field' %>
		<%= f.submit 'Änderungen speichern', class: 'btn btn-green' %>
		<% end %>
	</div>
	<div class="card">
		<h3>Abschnitt hinzufügen</h3>
		<%= form_for(:blog_paragraph, url: backoffice_new_blog_paragraph_path(@blog)) do |f| %>
			<%= f.text_field :title, class: 'form-field' %>
			<%= f.text_area :text, class: 'form-field' %>
			<%= f.submit 'hinzufügen!', class: 'btn btn-green' %>
		<% end %>
	</div>
</div>
<div class="row">
	<% @blog.blog_paragraphs.each do |bp| %>
	<div class="card">
		<h3>Abschnitt bearbeiten</h3>
		<%= form_for(:blog_paragraph, url: backoffice_edit_blog_paragraph_path(bp.id)) do |f| %>
			<%= f.text_field :title, class: 'form-field', value: bp.title %>
			<%= f.text_area :text, class: 'form-field', value: bp.text %>
			<%= f.submit 'Änderungen speichern!', class: 'btn btn-green' %>
		<% end %>
	</div>
	<% end %>
</div>
<div class="popup" id="popup">
   	<div class="img-container">
   		<%= image_tag '', id: 'root_image' %>
   	</div>
    <div class="form-group center">
    	<div class="btn btn-green" id="crop">speichern</div>
    </div>
    <div class="close" onclick="hidePopup()"><i class="fas fa-times"></i></div>
</div>
<script>
	function showPopup() {
        $('#popup').show();
    }
    function hidePopup() {
        $('#popup').hide();
    }
	(function ($) {
	  $.each(['show', 'hide'], function (i, ev) {
	    var el = $.fn[ev];
	    $.fn[ev] = function () {
	      this.trigger(ev);
	      return el.apply(this, arguments);
	    };
	  });
	})(jQuery);
	var inputAvatar = document.getElementById('blog_image');
	var image = document.getElementById('root_image');
	
	inputAvatar.addEventListener('change', function(e) {
		var files = e.target.files;
		var done = function(url) {
			inputAvatar.value = '';
			image.src = url;
			$('#popup').show();
		};
		var reader, file, url;
		if(files && files.length > 0) {
			file = files[0];
			if(URL) {
				done(URL.createObjectURL(file));
			} else if(FileReader) {
				reader = new FileReader();
				reader.onload = function(e) {
					done(reader.result);
				}
				reader.readAsDataURL(file);
			}
		}
	})
	$('#popup').on('show', function() {
		cropper = new Cropper(image, {
			aspectRatio: 2,	
		});
	})
	$('#popup').on('hide', function() {
		cropper.destroy();
		cropper = null;
	})
	$('#crop').on('click', function() {
		var initialURL, canvas;
		if(cropper) {
			canvas = cropper.getCroppedCanvas({
				fillColor: "white"
			});
			initalURL = blogIMG.src;
			blogIMG.src = canvas.toDataURL();
			canvas.toBlob(function(blob) {
				var date = new Date().getTime();
				var file = new window.File([blob], 'blog_'+date+'.jpg', {type: 'image/jpg'});
				var formData = new FormData();
				formData.append('file', file);
				uploadImage(formData);
			});
		};
	})
	function uploadImage(formData) {
		var url = '<%= backoffice_update_blog_image_path(@blog) %>';
		$.ajax({
			url: url,
			type: 'put',
			cache: false,
			async: true,
			contentType: false,
			processData: false,
			data: formData,
			beforeSend: function(xhr) { xhr.setRequestHeader('X-CSRF-Token', $('meta[name="csrf-token"]').attr('content')) },
			success: function(res) {
				formData = new FormData();
				$('#blogIMG').data('url', res.file);
				$('#popup').hide();
			}
		})	
	}
</script>

app/views/backoffice/game.html.erb
<h1>Pitch Übersicht - <%= @game.team.name %> - <%= @game.created_at.strftime('%d.%m.%Y') %></h1>

<div class="row">
<div class="card">
	<h3>Pitch Bewertung</h3>
	<table>
		<tr>
			<th>Gesamt</th>
			<td><%= @game.game_rating ? @game.game_rating.ges : '' %></td>
		</tr>
		<tr>
			<th>Spontanität</th>
			<td><%= @game.game_rating ? @game.game_rating.spontan : '' %></td>
		</tr>
		<tr>
			<th>Kreativität</th>
			<td><%= @game.game_rating ? @game.game_rating.creative : '' %></td>
		</tr>
		<tr>
			<th>Körpersprache</th>
			<td><%= @game.game_rating ? @game.game_rating.body : '' %></td>
		</tr>
		<tr>
			<th>Rhetorik</th>
			<td><%= @game.game_rating ? @game.game_rating.rhetoric : '' %></td>
		</tr>
	</table>
</div>
<div class="card">
	<h3>Datum ändern</h3>
	<%= form_for(:game, url: backoffice_edit_game_path(@game)) do |f| %>
		<%= f.date_field :created_at, class: 'form-field' %>
		<%= f.submit 'speichern', class: 'btn btn-green' %>
	<% end %>
</div>
</div>

<div class="table">
	<h3>Pitches</h3>
	<table>
		<thead>
			<tr>
				<th>Spieler</th>
				<th>Wort</th>
				<th>Spontanität</th>
				<th>Kreativität</th>
				<th>Körpersprache</th>
				<th>Rhetorik</th>
				<th>Gesamt</th>
				<th></th>
			</tr>
		</thead>
		<tbody>
			<% if @turn = @game.turns.find_by(user_id: nil) %>
				<%= form_for(:rating, url: backoffice_edit_rating_path(@turn.id)) do |f| %>
				<%= f.hidden_field :site, value: 'backoffice_game' %>
				<% @rating = @turn.turn_rating %>
				<tr class="red">
					<td><%= @turn.findUser.fname + ' ' + @turn.findUser.lname %></td>
					<td><%= Word.find_by(id: @turn.word_id) ? Word.find_by(id: @turn.word_id).name : '' %></td>
					<td><%= f.number_field :spontan, class: 'form-field' %></td>
					<td><%= f.number_field :creative, class: 'form-field' %></td>
					<td><%= f.number_field :body, class: 'form-field' %></td>
					<td><%= f.number_field :rhetoric, class: 'form-field' %></td>
					<td><%= @rating.nil? ? '' : @rating.ges %></td>
					<td><%= link_to '', backoffice_destroy_turn_path(@turn), class: 'far fa-trash-alt' %></td>
				</tr>
				<% end %>
			<% end %>
			<% @game.turns.where.not(user_id: nil).each do |t| %>
			<%= form_for(:rating, url: backoffice_edit_rating_path(t.id)) do |f| %>
				<%= f.hidden_field :site, value: 'backoffice_game' %>
				<% @rating = t.turn_rating %>
				<tr>
					<td onclick="redirect(<%= t.user_id %>)"><%= t.findUser.fname + ' ' + t.findUser.lname %></td>
					<td onclick="redirect(<%= t.user_id %>)"><%= Word.find_by(id: t.word_id) ? Word.find_by(id: t.word_id).name : '' %></td>
					<td><%= f.number_field :spontan, class: 'form-field' %></td>
					<td><%= f.number_field :creative, class: 'form-field' %></td>
					<td><%= f.number_field :body, class: 'form-field' %></td>
					<td><%= f.number_field :rhetoric, class: 'form-field' %></td>
					<td onclick="redirect(<%= t.user_id %>)"><%= @rating.nil? ? '' : @rating.ges %></td>
					<td><%= link_to '', backoffice_destroy_turn_path(t.id), class: 'far fa-trash-alt' %></td>
				</tr>
			<% end %>
			<% end %>
		</tbody>
	</table>
</div>
<script>
	function redirect(user_id) {
		var URL = "<%= backoffice_users_url(@admin) %>";
        location.replace(URL + '/' + user_id);
    }
</script>

app/views/backoffice/user.html.erb
<h1><%= @user.fname %> <%= @user.lname %> - Spieler Übersicht</h1>
<div class="row">

	<div class="card">
		<h3>User</h3>
		<%= form_for(:user, url: backoffice_edit_user_path(@user)) do |f| %>
		<table>
			<tr>
				<th>Vorname</th>
				<td><%= f.text_field :fname, class: 'form-field' %></td>
			</tr>
			<tr>
				<th>Nachname</th>
				<td><%= f.text_field :lname, class: 'form-field' %></td>
			</tr>
			<tr>
				<th>Email</th>
				<td><%= f.email_field :email, class: 'form-field' %></td>
			</tr>
			<tr>
				<th>Passwort</th>
				<td><%= f.password_field :password, class: 'form-field' %></td>
			</tr>
		</table>
		<%= f.submit 'Änderungen speichern', class: 'btn btn-green' %>
		<% end %>
	</div>

	<div class="card">
		<h3>Team</h3>
		<%= form_for(:user, url: backoffice_edit_user_path(@user)) do |f| %>
		<input type="hidden" name="user[teams][]" value="" checked>
		<table>
			<% @admin.teams.each do |t| %>
			<tr>
				<th><%= t.name %></th>
				<% if TeamUser.where(team_id: t.id, user_id: @user.id).count == 1 %>
				<td><input type="checkbox" name="user[teams][]" value="<%= t.id %>" checked id="team_users_<%= t.id %>"></td>
				<% else %>
				<td><input type="checkbox" name="user[teams][]" value="<%= t.id %>" id="team_users_<%= t.id %>"></td>
				<% end %>
			</tr>
			<% end %>
		</table>
		<%= f.submit 'Änderungen speichern', class: 'btn btn-green' %>
		<% end %>
	</div>

	<div class="card">
		<h3>Bilder</h3>
		<%= form_for(:user, url: backoffice_edit_user_path(@user)) do |f| %>
		<div class="avatar">
			<label for="user_avatar">
				<%= image_tag @user.avatar? ? @user.avatar.quad.url : '', id: 'avatar' %>
			</label>
			<%= f.file_field :avatar %>
		</div>
		<% end %>
	</div>
	
	<div class="card">
		<h3>Bewertung</h3>
		<table>
			<tr>
				<th>Gesamt</th>
				<td><%= @user.user_rating ? @user.user_rating.ges : '' %></td>
			</tr>
			<tr>
				<th>Spontanität</th>
				<td><%= @user.user_rating ? @user.user_rating.spontan : '' %></td>
			</tr>
			<tr>
				<th>Kreativität</th>
				<td><%= @user.user_rating ? @user.user_rating.creative : '' %></td>
			</tr>
			<tr>
				<th>Körpersprache</th>
				<td><%= @user.user_rating ? @user.user_rating.body : '' %></td>
			</tr>
			<tr>
				<th>Rhetorik</th>
				<td><%= @user.user_rating ? @user.user_rating.rhetoric : '' %></td>
			</tr>
		</table>
	</div>
</div>

<div class="table">
	<h3>Spiele</h3>
	<table>
		<thead>
			<tr>
				<th>Datum</th>
				<th>Wort</th>
				<th>Spontanität</th>
				<th>Kreativität</th>
				<th>Körpersprache</th>
				<th>Rhetoric</th>
				<th>Gesamt</th>
				<th></th>
			</tr>
		</thead>
		<tbody>
			<% @user.turns.each do |t| %>
			<%= form_for(:rating, url: backoffice_edit_rating_path(t.id)) do |f| %>W
				<%= f.hidden_field :site, value: 'backoffice_user' %>
				<% @rating = t.turn_rating %>
				<tr>
					<td onclick="redirect(<%= t.game_id %>)"><%= t.created_at.strftime('%d.%m.%Y') %></td>
					<td onclick="redirect(<%= t.game_id %>)"><%= Word.find_by(id: t.word_id) ? Word.find_by(id: t.word_id).name : '' %></td>
					<td><%= f.number_field :spontan, class: 'form-field' %></td>
					<td><%= f.number_field :creative, class: 'form-field' %></td>
					<td><%= f.number_field :body, class: 'form-field' %></td>
					<td><%= f.number_field :rhetoric, class: 'form-field' %></td>
					<td onclick="redirect(<%= t.game_id %>)"><%= @rating ? @rating.ges : '' %></td>
					<td><%= link_to '', backoffice_destroy_turn_path(t.id, site: 'user'), class: 'far fa-trash-alt' %></td>
				</tr>
				<%= f.submit '', style: 'display: none'%>
			<% end %>
			<% end %>
		</tbody>
	</table>
</div>

<div class="popup" id="popup">
   	<div class="img-container">
   		<%= image_tag '', id: 'user_image' %>
   	</div>
    <div class="form-group center">
    	<div class="btn btn-green" id="crop">speichern</div>
    </div>
    <div class="close" onclick="hidePopup()"><i class="fas fa-times"></i></div>
</div>
<script>
	function showPopup() {
        $('#popup').show();
    }
    function hidePopup() {
        $('#popup').hide();
    }
	(function ($) {
	  $.each(['show', 'hide'], function (i, ev) {
	    var el = $.fn[ev];
	    $.fn[ev] = function () {
	      this.trigger(ev);
	      return el.apply(this, arguments);
	    };
	  });
	})(jQuery);
	var inputAvatar = document.getElementById('user_avatar');
	var image = document.getElementById('user_image');
	
	inputAvatar.addEventListener('change', function(e) {
		var files = e.target.files;
		var done = function(url) {
			inputAvatar.value = '';
			image.src = url;
			$('#popup').show();
		};
		var reader, file, url;
		if(files && files.length > 0) {
			file = files[0];
			if(URL) {
				done(URL.createObjectURL(file));
			} else if(FileReader) {
				reader = new FileReader();
				reader.onload = function(e) {
					done(reader.result);
				}
				reader.readAsDataURL(file);
			}
		}
	})
	$('#popup').on('show', function() {
		cropper = new Cropper(image, {
			aspectRatio: 1,	
		});
	})
	$('#popup').on('hide', function() {
		cropper.destroy();
		cropper = null;
	})
	$('#crop').on('click', function() {
		var initialURL, canvas;
		if(cropper) {
			canvas = cropper.getCroppedCanvas({
				fillColor: "white"
			});
			initalURL = avatar.src;
			avatar.src = canvas.toDataURL();
			canvas.toBlob(function(blob) {
				var date = new Date().getTime();
				var file = new window.File([blob], 'avatar_'+date+'.jpg', {type: 'image/jpg'});
				var formData = new FormData();
				formData.append('file', file);
				uploadImage('avatar', formData);
			});
		};
	})
	function uploadImage(img, formData) {
		var url = '<%= backoffice_update_user_avatar_path(@user) %>';
		$.ajax({
			url: url,
			type: 'put',
			cache: false,
			async: true,
			contentType: false,
			processData: false,
			data: formData,
			beforeSend: function(xhr) { xhr.setRequestHeader('X-CSRF-Token', $('meta[name="csrf-token"]').attr('content')) },
			success: function(res) {
				formData = new FormData();
				$('#avatar').data('url', res.file);
				$('#popup').hide();
			}
		})	
	}
	function redirect(game_id) {
		var URL = "<%= backoffice_games_url(@admin) %>";
        location.replace(URL + '/' + game_id);
    }
</script>