config/routes.rb
Rails.application.routes.draw do
  devise_for :games
  devise_for :users
  devise_for :admins, controllers: { registrations: 'admins/registrations', sessions: 'admins/sessions', passwords: 'admins/passwords', confirmations: 'admins/confirmations', unlocks: 'admins/unlocks'}
  resource :cards
  resource :plans

  # root to: 'games#show'
  patch 'game_mobile_user/accept_user/:user_id', to: 'game_mobile_user#accept_user', as: 'accept_user'
  patch 'game_mobile_user/reject_user/:user_id', to: 'game_mobile_user#reject_user', as: 'reject_user'
 
###########
# Landing #
###########
  root 'landing#index'
  get 'admins/:admin_id/confirm', to: "landing#after_confirm", as: 'admin_after_confirm'
  get 'cookies', to: 'landing#accept_cookies', as: 'accept_cookies'
  get '/contact', to: 'landing#contact', as: 'contact'
  get 'product', to: 'landing#product', as: 'product'
  get 'datenschutz', to: 'landing#datenschutz', as: 'datenschutz'
  get 'impressum', to: 'landing#impressum', as: 'impressum'
  get 'blog', to: 'landing#blog', as: 'blog'
  get 'blog/:blog_id', to: 'landing#show_blog', as: 'show_blog'
	
  get 'landing/ended_game', to: 'landing#ended_game', as: 'landing_ended_game'

  get '/byebye', to: 'landing#byebye', as: 'byebye'
  # patch 'verification/verify_token' ,to: 'verification#verify_token' , as:'verify_token'
  get 'admins/register', to: 'landing#register', as: 'register'
  get 'admins/signup/:v_id', to: 'landing#signup' , as: 'edit_next_admin'
  patch 'admins/update_admin/:v_id', to: 'landing#update_admin', as: 'update_admin'
  patch 'admins/update_admin_details/:v_id', to: 'landing#update_admin_details', as: 'update_admin_details'

  get 'coaches/info', to: 'landing#coach', as: 'coach_info'
  # get '/verfication/:token' , to: 'verification#token' , as: 'verification_token'
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
########
# Game #
########

#################
# Admin Desktop #
#################

  get 'games/wait', to: 'game_desktop_admin#wait', as: 'gda_wait'
  get 'games/intro', to: 'game_desktop_admin#intro', as: 'gda_intro'
  get 'games/youtube_video', to: 'game_desktop_admin#youtube_video', as: 'gda_youtube'
  get 'games/choose', to: 'game_desktop_admin#choose', as: 'gda_choose'
  get 'games/turn', to: 'game_desktop_admin#turn', as: 'gda_turn'
  get 'games/error', to: 'game_desktop_admin#error', as: 'gea_turn'
  get 'video_testing', to: 'game_mobile_admin#video_testing'
  get 'games/play', to: 'game_desktop_admin#play', as: 'gda_play'
  get 'games/rate', to: 'game_desktop_admin#rate', as: 'gda_rate'
  get 'games/rating', to: 'game_desktop_admin#rating', as: 'gda_rating'
  get 'games/skip_rating', to: 'game_desktop_admin#skip_rating', as: 'gda_skip_rating'
  get 'games/bestlist', to: 'game_desktop_admin#bestlist', as: 'gda_bestlist'
  get 'games/ended', to: 'game_desktop_admin#ended', as: 'gda_ended'
  get 'games/ended_game', to: 'game_desktop_admin#ended_game', as: 'gda_ended_game'
  get 'games/replay', to: 'game_desktop_admin#replay', as: 'gda_replay'
    
  get 'games/after_rating', to: 'game_desktop_admin#after_rating', as: 'gda_after_rating'
  get 'games/video_uploaded_status', to: 'game_desktop_admin#video_uploaded_status', as: 'gda_video_uploaded_status'
  

################
# Admin Mobile #
################

  
  get 'mobile/admins/:password', to: 'game_mobile_admin#new', as: 'gma_start'
  post 'mobile/admins/:password', to: 'game_mobile_admin#create'
  get 'mobile/admin/avatar', to: 'game_mobile_admin#new_avatar', as: 'gma_new_avatar'
  post 'mobile/admin/avatar', to: 'game_mobile_admin#create_avatar'
  get 'mobile/admin/new_turn', to: 'game_mobile_admin#new_turn', as: 'gma_new_turn'
  post 'mobile/admin/new_turn', to: 'game_mobile_admin#create_turn'
    
  get 'mobile/admin/wait', to: 'game_mobile_admin#wait', as: 'gma_wait'
  post 'mobile/admin/after_wait', to: 'game_mobile_admin#after_wait', as: 'gma_after_wait'
  post 'mobile/admin/before_intro', to: 'game_mobile_admin#before_intro', as: 'gma_before_intro'
  get 'mobile/admin/intro', to: 'game_mobile_admin#intro', as: 'gma_intro'
  get 'mobile/admin/select_user', to: 'game_mobile_admin#choose_rating_user', as: 'gma_choose_rating_user'
  get 'mobile/admin/youtube_video', to: 'game_mobile_admin#youtube_video', as: 'gma_youtube'
  get 'mobile/admin/error', to: 'game_mobile_admin#error', as: 'gea_mobile'
  get 'mobile/admin/choose', to: 'game_mobile_admin#choose', as: 'gma_choose'
  get 'mobile/admin/choosen/:turn_id', to: 'game_mobile_admin#choosen', as: 'gma_choosen'
  get 'mobile/admin/turn', to: 'game_mobile_admin#turn', as: 'gma_turn'
  get 'mobile/admin/play', to: 'game_mobile_admin#play', as: 'gma_play'
  get 'mobile/admin/react', to: 'game_mobile_admin#react', as: 'gma_react'
  post 'mobile/admin/upload', to: 'game_mobile_admin#save_video', as: 'gpitchsave_play'
  get 'mobile/admin/video_cancel', to: 'game_mobile_admin#video_cancel',as: 'cancel_video_uploading'
  get 'mobile/admin/rate', to: 'game_mobile_admin#rate', as: 'gma_rate'
  get 'mobile/admin/rated', to: 'game_mobile_admin#rated', as: 'gma_rated'
  get 'mobile/admin/rating', to: 'game_mobile_admin#rating', as: 'gma_rating'
  get 'mobile/admin/skip_rating', to: 'game_mobile_admin#skip_rating', as: 'gma_skip_rating'
  get 'mobile/admin/bestlist', to: 'game_mobile_admin#bestlist', as: 'gma_bestlist'
  get 'mobile/admin/replay', to: 'game_mobile_admin#replay', as: 'gma_replay'
  get 'mobile/admin/ended', to: 'game_mobile_admin#ended', as: 'gma_ended'
  get 'mobile/admin/ended_game', to: 'game_mobile_admin#ended_game', as: 'gma_ended_game'
  get 'mobile/admin/after_rating', to: 'game_mobile_admin#after_rating', as: 'gma_after_rating'
  post 'mobile/admin/update_video_status', to: 'game_mobile_admin#update_video_status', as: 'gma_update_video_status'

    
###############
# User Mobile #
###############
    
  get 'mobile/user/game', to: 'game_mobile_user#new', as: 'gmu_password'
  post 'mobile/user/game', to: 'game_mobile_user#create'

  get 'mobile/user/name', to: 'game_mobile_user#new_name', as: 'gmu_new_name'
  post 'mobile/user/name', to: 'game_mobile_user#create_name'
    
  get 'mobile/user/company', to: 'game_mobile_user#new_company', as: 'gmu_new_company'
  post 'mobile/user/company', to: 'game_mobile_user#create_company'
    
  get 'mobile/user/avatar', to: 'game_mobile_user#new_avatar', as: 'gmu_new_avatar'
  post 'mobile/user/avatar', to: 'game_mobile_user#create_avatar'
    
  get 'mobile/user/game/new_turn', to: 'game_mobile_user#new_turn', as: 'gmu_new_turn'
  post 'mobile/user/game/new_turn', to: 'game_mobile_user#create_turn'
  get 'mobile/user/game/vidoe_uploading', to: 'game_mobile_user#video_uploading', as: 'gmu_video_check'
  get 'mobile/user/game/wait', to: 'game_mobile_user#wait', as: 'gmu_wait'
  get 'mobile/user/game/intro', to: 'game_mobile_user#intro', as: 'gmu_intro'
  get 'mobile/user/game/choose', to: 'game_mobile_user#choose', as: 'gmu_choose'
  get 'mobile/user/game/choosen/:turn_id', to: 'game_mobile_user#choosen', as: 'gmu_choosen'
  get 'mobile/user/game/turn', to: 'game_mobile_user#turn', as: 'gmu_turn'
  get 'mobile/user/game/play', to: 'game_mobile_user#play', as: 'gmu_play'
  get 'mobile/user/game/react', to: 'game_mobile_user#react', as: 'gmu_react'
  get 'mobile/user/game/rate', to: 'game_mobile_user#rate', as: 'gmu_rate'
  get 'mobile/user/game/rated', to: 'game_mobile_user#rated', as: 'gmu_rated'
  get 'mobile/user/game/rating', to: 'game_mobile_user#rating', as: 'gmu_rating'
  get 'mobile/user/game/skip_rating', to: 'game_mobile_user#skip_rating', as: 'gmu_skip_rating'
  get 'mobile/user/game/bestlist', to: 'game_mobile_user#bestlist', as: 'gmu_bestlist'
  get 'mobile/user/game/replay', to: 'game_mobile_user#replay', as: 'gmu_replay'
  get 'mobile/user/game/ended', to: 'game_mobile_user#ended', as: 'gmu_ended'
  get 'mobile/user/game/ended_game', to: 'game_mobile_user#ended_game', as: 'gmu_ended_game'
	
############
# Vertrieb #
############
	
  get '/vertrieb', to: 'vertrieb#new', as: 'vertrieb'
  post 'vertrieb/new', to: 'vertrieb#create', as: 'new_vertrieb'
  post 'vertrieb/login', to: 'vertrieb#login', as: 'login_vertrieb'
 
  get 'vertrieb/start', to: 'vertrieb#start', as: 'start_vertrieb'
  get 'vertrieb/proceed', to: 'vertrieb#proceed', as: 'proceed_vertrieb'
	
  get "vertrieb/game_wait", to: "vertrieb#game_wait", as: 'game_wait_vertrieb'
  get 'vertrieb/game_choose', to: 'vertrieb#game_choose', as: 'game_choose_vertrieb'
  get 'vertrieb/game_turn', to: 'vertrieb#game_turn', as: 'game_turn_vertrieb'
  get 'vertrieb/game_play', to: 'vertrieb#game_play', as: 'game_play_vertrieb'
  get 'vertrieb/game_rate', to: 'vertrieb#game_rate', as: 'game_rate_vertrieb'
  get 'vertrieb/game_rated', to: "vertrieb#game_rated", as: 'game_rated_vertrieb'
  get 'vertrieb/game_bestlist', to: 'vertrieb#game_bestlist', as: 'game_bestlist_vertrieb'
	
  get 'vertrieb/dash_customize', to: 'vertrieb#dash_customize', as: 'dash_customize_vertrieb'
  get 'vertrieb/dash_lets_pitch', to: 'vertrieb#dash_lets_pitch', as: 'dash_lets_pitch_vertrieb'
  get 'vertrieb/dash_lets_pitch2', to: 'vertrieb#dash_lets_pitch2', as: 'dash_lets_pitch2_vertrieb'
  get 'vertrieb/dash_user_stats', to: 'vertrieb#dash_user_stats', as: 'dash_user_stats_vertrieb'
  get 'vertrieb/dash_users', to: 'vertrieb#dash_users', as: 'dash_users_vertrieb'
  get 'vertrieb/dash_videoanalyse', to: 'vertrieb#dash_videoanalyse', as: 'dash_videoanalyse_vertrieb'
	
  get 'vertrieb/ended', to: 'vertrieb#ended', as: 'ended_vertrieb'
    
####################################################################################
#############
# Dashboard #
#############

##############
# Backoffice #
##############
  
  get 'backoffice', to: 'backoffice#index', as: 'backoffice'
	
  get 'backoffice/admins', to: 'backoffice#admins', as: 'backoffice_admins'
  get 'backoffice/admins/:admin_id', to: 'backoffice#admin', as: 'backoffice_admin'

app/views/game_mobile_admin/_header.html.erb
<% @game = @game1 if @game1 %>
<% @game1 = @game if @game %>
<div class="menu menu-position nunito-extrabold">
	<span class="menu-logo"><img width="144" src="<%= image_url 'logo-m.png' %>"></span>
	<% if @game %>
	<p><%= @game.team.name %></p>
	<% else %>
	<p><%= @game1.team.name %></p>
	<% end %>
	<% if can %>
		<button type="button" id="list" class="btn btn-primary btn-menu" data-toggle="modal" data-target="#myModal">
		  <span></span>
		  <span></span>
		  <span></span>
		</button>
    <% elsif @game && @game.admin.logo.present? %>
      <%= image_tag @game.admin.logo.url, class: 'company' %>
    <% elsif @game1 && @game1.admin.logo.present? %>
      <%= image_tag @game.admin.logo.url, class: 'company' %>
	<% end %>
</div>

app/views/game_mobile_admin/_rating_count.html.erb
<%= @ratings_count %>/<%= @player_count %> <br>
haben bewertet!

app/views/game_mobile_admin/bestlist.html.erb
<%= render partial: 'header' , locals: {can: false}%>
<div class="head">
    <h1>Tolle Runde!</h1>
</div>
<div class="middle">
    <%= image_tag @admin.avatar.quad.url || 'defaults/wolf.jpg', class: 'mid-img green pulse' %>
</div>
<div class="bottom">
   <a href="<%= gma_replay_path %>" class="pol-bg" style="display: inline;"><i class="fas fa-redo"></i></a>
   <a href="<%= gma_ended_game_path %>" class="pol-bg" style="display: inline;" data-confirm="Bist du sicher, dass du keine neue Runde starten möchtest?"><i class="fas fa-times"></i></a>
</div>
<script>
	checkOrientation();
 	window.addEventListener('resize', checkOrientation);
</script>

app/views/game_mobile_admin/choose.html.erb
<%= render partial: 'header' , locals: {can: false}%>
<div class="head">
    <h1 class="nunito-bold">Jetzt wählen!</h1>
</div>
<div class="middle">
    <%= image_tag @turn1.findUser.avatar.quad.url, class: 'mid-img-left blue' %>
    <%= image_tag @turn2.findUser.avatar.quad.url, class: 'mid-img-right blue' %>
    <%= link_to '', gma_choosen_path(@turn1),class: 'mid-img-left' %>
    <%= link_to '', gma_choosen_path(@turn2), class: 'mid-img-right' %>
</div>
<div class="bottom">
</div>
<script>
	checkOrientation();
 	window.addEventListener('resize', checkOrientation);
</script>

app/views/game_mobile_admin/choosen.html.erb
<%= render partial: 'header' , locals: {can: false}%>
<div class="head">
    <h1 class="nunito-bold">Du hast für <%= @turn.findUser.fname %> gestimmt!</h1>
</div>
<div class="middle">
    <%= image_tag @turn.findUser.avatar.quad.url, class: 'mid-img green pulse' %>
</div>
<div class="bottom">
    <%= link_to 'weiter!', gma_turn_url , id: 'play', class: "nunito-regular" %>
</div>
<script>
	checkOrientation();
 	window.addEventListener('resize', checkOrientation);
</script>

app/views/game_mobile_admin/error.html.erb
<%= render partial: 'header' , locals: {can: false}%>
<div class="head">
    <h1 class="nunito-bold">Nicht genug Spieler,</h1>
    <h3 class="nunito-regular">um den Pitch zu starten!</h3>
</div>
<div class="bottom">
    <%= link_to 'zurück!', gma_wait_path, class: 'nunito-regular' %>
</div>
<script>
	checkOrientation();
 	window.addEventListener('resize', checkOrientation);
</script>

app/views/game_mobile_admin/new.html.erb
<%= render partial: 'header' , locals: {can: false}%>
<div class="head">
    <h1>Bitte logge dich ein!</h1>
</div>
<%= form_for(:admin, url: gma_email_check_path, html: {autocomplete: 'off'}) do |f| %>
<div class="middle-form">
    <div class="row">
        
        <div class="col-12 red">
            <%= f.email_field :email, placeholder: 'E-mail', class: 'form-field', onchange: 'enterName()' %>
        </div>
        <% else %>
        <div class="col-12 red">
            <%= f.email_field :email, placeholder: 'E-mail', class: 'form-field', onchange: 'enterName()' %>
        </div>
        <% end %>
    </div>
</div>
<div class="bottom">
    <%= link_to "weiter!", '', class: 'link nunito-regular', id: 'fake' %>
    <%= f.submit 'weiter!', class: 'link pulse nunito-regular', id: 'summit', style: 'display: none' %>
</div>
<% end %>


<script>
    function enterName() {
        $('#fake').hide();
        $('#summit').show();
    }
	window.removeEventListener('resize', checkOrientation);
</script>

app/views/game_mobile_admin/new_avatar.html.erb
<%= render partial: 'header' , locals: {can: false}%>
<% if @admin.avatar? %>
<div class="head">    
    <h1 class="nunito-bold">Wow!</h1>
    <h3 class="nunito-regular">Drücke auf "weiter" oder auf das <br> Bild für einen neuen Versuch!</h3>
</div>
<% else %>
<div class="head nunito-bold">
    <h1 class="nunito-bold">Bild hinzufügen!</h1>
    <h3 class="nunito-regular">Drücke das Plus, um ein Foto zu machen oder ein bestehendes Bild von dir hochzuladen.</h3>
</div>
<% end %>
<div class="middle">
      <%= form_for(:admin, url: gma_new_avatar_path) do |f| %>
        <% if @admin.avatar? %>
            <label for="admin_avatar" id="admin_pic">
                <%= image_tag @admin.avatar.quad.url, class: 'mid-img blue' %>
            </label>
            <div class="add">
                <i class="fas fa-check-circle"></i>
            </div>
        <% else %>
            <label for="admin_avatar" id='admin_pic'>
                <%= image_tag 'game/plus.png', class: 'mid-img pulse' %>
            </label>
        <% end %>
        <%= f.file_field :avatar, onchange: 'auto()' %>
        <%= f.submit '', style: 'display:none'%>
      <% end %>
  </div>
  <% if @admin.avatar? %>
    <div class="bottom bottom-play">
      <%= form_for(:admin, url: gma_new_turn_path, method: 'get') do |f| %>
        <div class="switch-box switch-box-vt" id="switch">
          <label class="switch">
            <input type="checkbox" id="start" value="rate" name="play" >
            <span class="slider round"></span>
          </label>
          <p class="text-for-switch nunito-regular" id=''>Ich möchte selbst nicht pitchen,<br> sondern nur bewerten</p>
        </div>
    </div>
    <div class="bottom">
    	<%= f.submit 'weiter!', class: 'link pulse nunito-regular' %>
    </div>
    <% end %>
  <% end %>

<script>
function auto() {
    $('form').submit();
    $('.bottom').show();
    $("form").replaceWith("<div class='spinner spinner1'></div>")
}
</script>
<script>
	checkOrientation();
 	window.addEventListener('resize', checkOrientation);
</script>

app/views/game_mobile_admin/rated.html.erb
<div id="count_channel" data-game-id="<%= @game.id %>" >
<%= render partial: 'header' , locals: {can: false}%>
<div class="head">
    <h1 class="nunito-bold">
    <% if @admin == @cur_user %>
        <%= @admin.fname %>, du wirst bewertet!
    <% else %>
        Bewertung abgegeben!
    <% end %>
    </h1>
</div>
<div class="middle" id="middle">
    <div class="row">
    	<div class="col-12 nunito-regular">
    		<%= @count.to_s + "/" + @turnCount.to_s %><br>
    		haben bewertet!
    	</div>
    </div>
</div>
<div class="bottom">
    <%= link_to 'weiter!', gma_rating_path, class: 'nunito-regular' %>
</div>
</div>
<script>
	checkOrientation();
 	window.addEventListener('resize', checkOrientation);
</script>

app/views/game_mobile_admin/rating.html.erb
<%= render partial: 'header' , locals: {can: false}%>
<div class="head">        
    <h1 class="nunito-bold">Hier ist die Bewertung!</h1>
</div>
<div class="middle">
    <%= image_tag @cur_user.avatar.quad.url || 'defaults/wolf.jpg', class: 'mid-img green pulse' %>
</div>
<div class="bottom">
    <%= link_to 'weiter!', gma_after_rating_path, class: 'nunito-regular' %>
</div>
<script>
	checkOrientation();
 	window.addEventListener('resize', checkOrientation);
</script>

app/views/game_mobile_admin/turn.html.erb
<%= render partial: 'header' , locals: {can: false}%>
<div class="head">
    <% if @admin == @cur_user %>
        <h1 class="nunito-bold"><%= @cur_user.fname %>, du bist dran!</h1>
    <% else %>
        <h1 class="nunito-bold"><%= @cur_user.fname %> ist dran!</h1>
    <% end %>
</div>
<div class="middle">
    <%= image_tag @cur_user.avatar.quad.url, class: 'mid-img green pulse' %>
</div>
<div class="bottom bottom-play">
    <div class="switch-box switch-box-vt" id="switch">
        <label class="switch">
            <input type="checkbox" id="start" value="is" >
            <span class="slider round"></span>
        </label>
        <p class="text-for-switch nunito-regular" id=''>Mit Video Starten</p>
    </div>
</div>
<div class="bottom">
	<%= link_to 'Pitch starten!', gma_play_url , id: 'play', class: 'nunito-regular' %>
</div>

<!-- <form action="/mobile/admin/upload" method="POST" enctype="multipart/form-data">
  
  <input id="video" type="file" name="file" accept="video/*"  class="video-file">
  <input type="submit" value="Submit">
</form>

<style>
    .spinner-div {
      top: 45% !important;
      position: absolute;
    }
  
    .spinner {
      height: auto !important;
      width: auto !important;
      left: calc(60% - 200px) !important;
    }
    #video-button{
      z-index: 555;
    }
  
    input[type='file'] {
      display: block !important;
    }
  
    .video-upload-wrapper {
      top: 78%;
    }
  
    .upload-btn-wrapper {
      display: flex;
      justify-content: center;
      align-items: center;
      position: relative;
      overflow: hidden;
    }
  
    .video-btn {
      border: 2px solid #1ddaaf;
      color: white;
      background-color: #1ddaaf;
      padding: 8px 20px;
      border-radius: 4.013vh;
      min-width: 30vh;
      font-size: 20px;
      font-size: 2.5vh;
      height: auto;
      line-height: 4vh;
      font-weight: bold;
    }
  
    .upload-btn-wrapper input[type=file] {
      position: absolute;
      left: 0;
      top: 0;
      right: 0;
      opacity: 0;
    }
  </style> -->

<script type="text/javascript">
    $("#start").on("change", function(e){
      var that = $(this);
      if(that.is(":checked")){
        try {
          // var stream =new MediaStream()
          // new MediaRecorder(stream)
          $(".text-for-switch").addClass("green-text")
        }
        catch(err) {
          $("#start").prop("checked", false);
          alert('sorry your browser does not support record-function \n Please use Chrome to have full functionality of Peter Pitch');
        }
      }else{
        $(".text-for-switch").removeClass("green-text")
      }
    })
    var redirect = false;
    $("#play").click(function(event){
        event.preventDefault();
        var $this = $(this);
        var href = $this.attr("href"),
        video = $("#start").prop("checked");
        window.location = href +"?video="+video;
    })
</script>
<script>
	checkOrientation();
 	window.addEventListener('resize', checkOrientation);
</script>

app/views/game_mobile_admin/youtube_video.html.erb
<section id="count_channel" data-game-id="<%= @game.id %>">
    <%= render partial: 'header' , locals: {can: false}%>
    <div class="head">
        <h1 class="nunito-bold">Video läuft...</h1>
    </div>
    <div class="middle">
        <% if @admin.avatar? %>
        <%= image_tag @admin.avatar.quad.url, class: 'mid-img green pulse' %>
        <% else %>
        <div class="mid-img green">
            <%= image_tag 'game/wolf_button.png', class: 'wolf pulse' %>
        </div>
        <% end %>
    </div>
    <div class="bottom">
        <%= link_to 'skip!', gma_choose_path, class: 'nunito-regular' %>
    </div>
</section>
<%= audio_tag('wait/ringdoor.mp3', id: 'ringdoor', muted: @game.mute_sound) %>

<script type="text/javascript">
    <% @pending_users.each do | user | %>
        modal = '<div style="display: none; z-index: 10000;"  class="modal modal-email" id="myModalAction<%=user.id.to_s %>" tabindex="-1" role="dialog" aria-labelledby="exampleModalLabel" aria-hidden="true"><div class="modal-dialog modal-dialog ml-3 modal-dialog-centered mr-3 mr-md-auto" role="document"><div class="modal-content"><div class="modal-header p-2"><button type="button" data-id="<%=user.id.to_s %>" class="close" data-dismiss="modal" aria-label="Close"><span class="x-btn" aria-hidden="true">&times;</span></button></div><div class="modal-body"><div class="mail-box d-flex flex-column flex-md-row align-items-md-center"><div class="mail-box-main d-flex flex-column flex-md-row align-items-md-center"><span class="req-img"><img src="<%= user.avatar.url %>"   /></span><span> <%= "#{user.fname}. #{user.lname}" %></span></div><div class="mail-btn mt-3 mt-md-0"><a class="btn btn-green btn-green-accept" data-remote=true rel="nofollow" data-method="patch" href="/game_mobile_user/accept_user/<%=user.id.to_s %>">Accept</a><a class="btn btn-green btn-green-reject" rel="nofollow" data-remote=true data-method="patch" href="/game_mobile_user/reject_user/<%=user.id.to_s %>">Reject</a></div></div></div></div></div></div>';        
        $("body").append(modal)
        $('#myModalAction<%=user.id.to_s %>').show();
    <% end %>

    $(".close").click(function () {
        let id = $(this).attr('data-id');
        $(`#myModalAction${id}`).hide()
    })
</script>
<script>
	checkOrientation();
 	window.addEventListener('resize', checkOrientation);
</script>